// 核心高考高频688词汇
// 适合高三复习使用
window.vocabulary688 = [
    // 1-50
    {id: 1, word: "personal", pos: "adj.", cn: "私人的，个人的", freq: 310, example: "This is my personal opinion."},
    {id: 2, word: "tie", pos: "v./n.", cn: "系，联系；关系", freq: 289, example: "Tie your shoelaces properly."},
    {id: 3, word: "still", pos: "adj./adv.", cn: "静止的；甚至，仍然", freq: 237, example: "Keep still for the photo."},
    {id: 4, word: "offer", pos: "v.", cn: "提供，出(价)；愿意(做某事)", freq: 228, example: "They offered me a job."},
    {id: 5, word: "addition", pos: "n.", cn: "增加", freq: 202, example: "In addition to math, she studies physics."},
    {id: 6, word: "success", pos: "n.", cn: "成功", freq: 188, example: "Success requires hard work."},
    {id: 7, word: "produce", pos: "v./n.", cn: "生产，引起；产品", freq: 187, example: "This factory produces cars."},
    {id: 8, word: "expect", pos: "v.", cn: "预料，预计；期待", freq: 185, example: "I expect you to be on time."},
    {id: 9, word: "cause", pos: "v./n.", cn: "引起；原因；事业；目标", freq: 178, example: "What caused the accident?"},
    {id: 10, word: "state", pos: "n./v./adj.", cn: "情形，状态；声明，陈述；国家的", freq: 177, example: "Please state your name."},
    {id: 11, word: "manage", pos: "v.", cn: "管理；设法做成(to)", freq: 169, example: "She manages a large team."},
    {id: 12, word: "directly", pos: "adv.", cn: "直接地", freq: 166, example: "Go directly to the office."},
    {id: 13, word: "improve", pos: "v.", cn: "改善，提高", freq: 165, example: "Practice will improve your skills."},
    {id: 14, word: "wonder", pos: "n./v.", cn: "奇迹；想知道；怀疑", freq: 162, example: "I wonder what happened."},
    {id: 15, word: "present", pos: "adj./v./n.", cn: "当前的，出席的；呈现；赠送；礼物", freq: 160, example: "Everyone was present at the meeting."},
    {id: 16, word: "underline", pos: "v.", cn: "在...下面划线；强调", freq: 160, example: "Underline the important words."},
    {id: 17, word: "mislead", pos: "v.", cn: "误导", freq: 159, example: "Don't let appearances mislead you."},
    {id: 18, word: "complete", pos: "v./adj.", cn: "完成；完成的", freq: 157, example: "Complete the task by Friday."},
    {id: 19, word: "lead", pos: "v./n.", cn: "导致(to)，带领；过(...的生活)；领头位置", freq: 154, example: "This road leads to the park."},
    {id: 20, word: "sensitive", pos: "adj.", cn: "敏感的", freq: 153, example: "She's sensitive to criticism."},
    {id: 21, word: "valuable", pos: "adj.", cn: "贵重的", freq: 147, example: "Time is valuable."},
    {id: 22, word: "courageous", pos: "adj.", cn: "勇敢的", freq: 146, example: "It was a courageous decision."},
    {id: 23, word: "tend", pos: "v.", cn: "趋向，照顾(to)", freq: 144, example: "Children tend to be curious."},
    {id: 24, word: "matter", pos: "n./v.", cn: "事情；要紧", freq: 141, example: "It doesn't matter."},
    {id: 25, word: "realise", pos: "v.", cn: "意识到，实现(梦想)", freq: 136, example: "I didn't realise you were here."},
    {id: 26, word: "acceptable", pos: "adj.", cn: "可接受的", freq: 131, example: "Your work is acceptable."},
    {id: 27, word: "consider", pos: "v.", cn: "考虑，认为", freq: 131, example: "Please consider my proposal."},
    {id: 28, word: "support", pos: "v./n.", cn: "支持", freq: 126, example: "I support your decision."},
    {id: 29, word: "fit", pos: "adj./v.", cn: "适宜的；健康的；安装(in)，适合", freq: 125, example: "These shoes don't fit."},
    {id: 30, word: "hang", pos: "v.", cn: "悬挂", freq: 124, example: "Hang your coat here."},
    {id: 31, word: "protect", pos: "v.", cn: "保护", freq: 123, example: "Protect the environment."},
    {id: 32, word: "professional", pos: "adj./n.", cn: "专业的；职业，专业", freq: 113, example: "He's a professional player."},
    {id: 33, word: "widen", pos: "v.", cn: "使变宽", freq: 112, example: "They plan to widen the road."},
    {id: 34, word: "require", pos: "v.", cn: "要求", freq: 105, example: "This job requires experience."},
    {id: 35, word: "creative", pos: "adj.", cn: "创造性的", freq: 104, example: "She has a creative mind."},
    {id: 36, word: "deal", pos: "v./n.", cn: "处理(with)；交易", freq: 104, example: "How do you deal with stress?"},
    {id: 37, word: "popularity", pos: "n.", cn: "普及，流行", freq: 100, example: "The app gained popularity quickly."},
    {id: 38, word: "attend", pos: "v.", cn: "出席，关心(to)；处理(to)", freq: 99, example: "Please attend the meeting."},
    {id: 39, word: "prefer", pos: "v.", cn: "更喜欢", freq: 98, example: "I prefer tea to coffee."},
    {id: 40, word: "wild", pos: "adj.", cn: "野生的", freq: 97, example: "Wild animals live in the forest."},
    {id: 41, word: "quality", pos: "n.", cn: "质量，品质", freq: 93, example: "We focus on quality, not quantity."},
    {id: 42, word: "perform", pos: "v.", cn: "执行，表演", freq: 91, example: "The band will perform tonight."},
    {id: 43, word: "promise", pos: "n./v.", cn: "诺言；允诺，答应", freq: 90, example: "Keep your promise."},
    {id: 44, word: "necessarily", pos: "adv.", cn: "必然地", freq: 90, example: "That's not necessarily true."},
    {id: 45, word: "store", pos: "v./n.", cn: "储存；商店", freq: 90, example: "Store the food in a cool place."},
    {id: 46, word: "general", pos: "adj.", cn: "普遍的", freq: 88, example: "In general, I agree with you."},
    {id: 47, word: "condition", pos: "n.", cn: "情况，条件", freq: 87, example: "The car is in good condition."},
    {id: 48, word: "vary", pos: "v.", cn: "改变，不同", freq: 87, example: "Prices vary from store to store."},
    {id: 49, word: "suffer", pos: "v.", cn: "遭受(from)", freq: 85, example: "Many people suffer from stress."},
    {id: 50, word: "speech", pos: "n.", cn: "演讲", freq: 84, example: "He gave a powerful speech."},

    // 51-100
    {id: 51, word: "respect", pos: "v./n.", cn: "尊敬，尊重", freq: 83, example: "We should respect our elders."},
    {id: 52, word: "disappoint", pos: "v.", cn: "使失望", freq: 82, example: "I don't want to disappoint you."},
    {id: 53, word: "simplify", pos: "v.", cn: "简化，使简单", freq: 82, example: "Can you simplify this explanation?"},
    {id: 54, word: "raise", pos: "v.", cn: "举起，筹集，提出", freq: 81, example: "Raise your hand if you know."},
    {id: 55, word: "refer", pos: "v.", cn: "涉及，提到；查阅(to)", freq: 80, example: "Please refer to page 10."},
    {id: 56, word: "achievement", pos: "n.", cn: "成就", freq: 79, example: "This is a great achievement."},
    {id: 57, word: "particular", pos: "adj.", cn: "特别的", freq: 79, example: "Pay particular attention to this."},
    {id: 58, word: "prevent", pos: "v.", cn: "阻止", freq: 78, example: "Exercise helps prevent disease."},
    {id: 59, word: "regular", pos: "adj.", cn: "有规律的，定期的", freq: 78, example: "Regular exercise is important."},
    {id: 60, word: "connect", pos: "v.", cn: "连接，联系(with)", freq: 78, example: "Connect the dots."},
    {id: 61, word: "subject", pos: "n./adj.", cn: "主题，实验对象；服从的", freq: 78, example: "What's your favorite subject?"},
    {id: 62, word: "physical", pos: "adj.", cn: "物质的，身体的", freq: 75, example: "Physical exercise is important."},
    {id: 63, word: "check", pos: "n./v.", cn: "支票，检查；核对", freq: 75, example: "Check your answers."},
    {id: 64, word: "position", pos: "n./v.", cn: "位置，立场；定位，安置", freq: 75, example: "What's your position on this issue?"},
    {id: 65, word: "concern", pos: "v.", cn: "关心(about)，涉及", freq: 74, example: "I'm concerned about your health."},
    {id: 66, word: "force", pos: "v./n.", cn: "强迫；力量", freq: 74, example: "Don't force yourself."},
    {id: 67, word: "satisfy", pos: "v.", cn: "使满意", freq: 74, example: "Nothing seems to satisfy him."},
    {id: 68, word: "organize", pos: "v.", cn: "组织，安排", freq: 71, example: "Let's organize a party."},
    {id: 69, word: "charge", pos: "n./v.", cn: "费用，指控；要价(for)，管理，充电", freq: 70, example: "How much do you charge?"},
    {id: 70, word: "favor", pos: "n./v.", cn: "好意；偏爱", freq: 70, example: "Can you do me a favor?"},
    {id: 71, word: "damage", pos: "v./n.", cn: "损害", freq: 70, example: "The storm caused serious damage."},
    {id: 72, word: "publish", pos: "v.", cn: "出版，发行", freq: 69, example: "When will you publish your book?"},
    {id: 73, word: "focus", pos: "n./v.", cn: "焦点；聚焦(on)", freq: 68, example: "Focus on your goals."},
    {id: 74, word: "affect", pos: "v.", cn: "影响", freq: 68, example: "How did it affect you?"},
    {id: 75, word: "feed", pos: "v.", cn: "喂养(on)", freq: 65, example: "Feed the cat twice a day."},
    {id: 76, word: "weigh", pos: "v.", cn: "称(重量)，重达", freq: 65, example: "How much do you weigh?"},
    {id: 77, word: "pressure", pos: "n.", cn: "压力，压强", freq: 64, example: "Work pressure is increasing."},
    {id: 78, word: "credit", pos: "n.", cn: "信用", freq: 64, example: "Give credit where it's due."},
    {id: 79, word: "visible", pos: "adj.", cn: "可见的", freq: 64, example: "The stars are visible tonight."},
    {id: 80, word: "operate", pos: "v.", cn: "操作，经营，动手术", freq: 63, example: "Can you operate this machine?"},
    {id: 81, word: "warn", pos: "v.", cn: "警告", freq: 62, example: "I warned you about this."},
    {id: 82, word: "relate", pos: "v.", cn: "有关联(to)，陈述", freq: 60, example: "How does this relate to our topic?"},
    {id: 83, word: "strength", pos: "n.", cn: "力量", freq: 60, example: "Unity is strength."},
    {id: 84, word: "stress", pos: "v./n.", cn: "强调；压力，强调", freq: 60, example: "Don't stress yourself too much."},
    {id: 85, word: "attack", pos: "n./v.", cn: "攻击", freq: 60, example: "The army launched an attack."},
    {id: 86, word: "determine", pos: "v.", cn: "下决心", freq: 60, example: "Determine your priorities."},
    {id: 87, word: "volunteer", pos: "n./v.", cn: "志愿者；(自愿)做", freq: 60, example: "I volunteer at the hospital."},
    {id: 88, word: "lack", pos: "n./v.", cn: "缺乏(of/in)", freq: 59, example: "They lack experience."},
    {id: 89, word: "equipment", pos: "n.", cn: "设备", freq: 59, example: "We need new equipment."},
    {id: 90, word: "expense", pos: "n.", cn: "花费", freq: 58, example: "Travel expenses are high."},
    {id: 91, word: "deliver", pos: "v.", cn: "递送，发表(演讲)", freq: 58, example: "They deliver pizza."},
    {id: 92, word: "compare", pos: "v.", cn: "比较(with)；比喻(to)", freq: 57, example: "Compare these two options."},
    {id: 93, word: "spread", pos: "v.", cn: "延伸，传播", freq: 57, example: "The news spread quickly."},
    {id: 94, word: "seek", pos: "v.", cn: "寻找", freq: 57, example: "Seek help when needed."},
    {id: 95, word: "distant", pos: "adj.", cn: "遥远的", freq: 56, example: "In the distant future."},
    {id: 96, word: "original", pos: "adj.", cn: "原始的，最初的", freq: 56, example: "This is the original version."},
    {id: 97, word: "impress", pos: "v.", cn: "使...有印象(on)", freq: 55, example: "Her speech impressed everyone."},
    {id: 98, word: "remind", pos: "v.", cn: "提醒(of)", freq: 54, example: "Remind me tomorrow."},
    {id: 99, word: "communicate", pos: "v.", cn: "交流(with)", freq: 54, example: "We need to communicate better."},
    {id: 100, word: "range", pos: "n./v.", cn: "范围；涉及(from...to...)", freq: 52, example: "Prices range from $10 to $50."},

    // 101-150
    {id: 101, word: "guidance", pos: "n.", cn: "指导", freq: 52, example: "Thank you for your guidance."},
    {id: 102, word: "avoid", pos: "v.", cn: "避免", freq: 51, example: "Avoid making the same mistake."},
    {id: 103, word: "opportunity", pos: "n.", cn: "机会", freq: 51, example: "This is a great opportunity."},
    {id: 104, word: "emotion", pos: "n.", cn: "情绪", freq: 51, example: "Control your emotions."},
    {id: 105, word: "equal", pos: "adj./v.", cn: "相等的；等于(to)", freq: 50, example: "All people are equal."},
    {id: 106, word: "contain", pos: "v.", cn: "包含", freq: 50, example: "This box contains books."},
    {id: 107, word: "hardly", pos: "adv.", cn: "几乎不", freq: 50, example: "I can hardly hear you."},
    {id: 108, word: "announce", pos: "v.", cn: "宣布", freq: 48, example: "They will announce the winner."},
    {id: 109, word: "reward", pos: "v./n.", cn: "奖赏；报酬", freq: 48, example: "Hard work brings rewards."},
    {id: 110, word: "desire", pos: "n./v.", cn: "渴望", freq: 48, example: "She has a strong desire to succeed."},
    {id: 111, word: "promote", pos: "v.", cn: "促进，促销，升迁", freq: 47, example: "Exercise promotes health."},
    {id: 112, word: "gather", pos: "v./n.", cn: "聚集", freq: 47, example: "People gathered in the square."},
    {id: 113, word: "similarity", pos: "n.", cn: "相似，类似", freq: 47, example: "There are many similarities."},
    {id: 114, word: "advance", pos: "n./adj.", cn: "前进；提前的", freq: 46, example: "Book tickets in advance."},
    {id: 115, word: "percent", pos: "n.", cn: "百分比", freq: 46, example: "Fifty percent agreed."},
    {id: 116, word: "character", pos: "n.", cn: "个性，人物", freq: 46, example: "She has a strong character."},
    {id: 117, word: "frighten", pos: "v.", cn: "使惊吓", freq: 45, example: "Don't frighten the children."},
    {id: 118, word: "accessible", pos: "adj.", cn: "易接近的；可得到的", freq: 44, example: "The website is accessible to all."},
    {id: 119, word: "potential", pos: "adj./n.", cn: "潜在的；潜力", freq: 44, example: "You have great potential."},
    {id: 120, word: "review", pos: "v./n.", cn: "复习；评论", freq: 44, example: "Let's review the lesson."},
    {id: 121, word: "replace", pos: "v.", cn: "取代", freq: 43, example: "Replace the old with the new."},
    {id: 122, word: "greedy", pos: "adj.", cn: "贪婪的", freq: 43, example: "Don't be greedy."},
    {id: 123, word: "shock", pos: "n./v.", cn: "震惊；使震惊", freq: 43, example: "The news shocked everyone."},
    {id: 124, word: "judge", pos: "v./n.", cn: "判断；法官，裁判", freq: 42, example: "Don't judge too quickly."},
    {id: 125, word: "praise", pos: "n./v.", cn: "称赞", freq: 42, example: "The teacher praised the students."},
    {id: 126, word: "recover", pos: "v.", cn: "恢复", freq: 42, example: "He's recovering from illness."},
    {id: 127, word: "confuse", pos: "v.", cn: "使困惑", freq: 42, example: "Don't confuse the issue."},
    {id: 128, word: "spot", pos: "n./v.", cn: "地点；发现", freq: 42, example: "I spotted an error."},
    {id: 129, word: "attempt", pos: "v./n.", cn: "企图，尝试(to)；试图", freq: 42, example: "This is my first attempt."},
    {id: 130, word: "available", pos: "adj.", cn: "可利用的(to)", freq: 42, example: "Is this seat available?"},
    {id: 131, word: "destruction", pos: "n.", cn: "破坏，毁灭", freq: 42, example: "War causes destruction."},
    {id: 132, word: "construct", pos: "v.", cn: "建造，构造", freq: 41, example: "They will construct a bridge."},
    {id: 133, word: "function", pos: "n./v.", cn: "功能；起作用", freq: 41, example: "What's the function of this button?"},
    {id: 134, word: "argument", pos: "n.", cn: "观点(on/about)，争论", freq: 41, example: "They had an argument."},
    {id: 135, word: "labor", pos: "n.", cn: "劳力", freq: 40, example: "Manual labor is hard work."},
    {id: 136, word: "private", pos: "adj.", cn: "私人的，秘密的", freq: 40, example: "This is private property."},
    {id: 137, word: "repeat", pos: "v.", cn: "重复", freq: 40, example: "Please repeat after me."},
    {id: 138, word: "spirit", pos: "n.", cn: "精神", freq: 40, example: "Team spirit is important."},
    {id: 139, word: "suppose", pos: "v.", cn: "假设，认为", freq: 40, example: "I suppose you're right."},
    {id: 140, word: "desert", pos: "n./v.", cn: "沙漠；遗弃", freq: 40, example: "The Sahara is a large desert."},
    {id: 141, word: "exchange", pos: "n./v.", cn: "交换(for)", freq: 39, example: "Let's exchange phone numbers."},
    {id: 142, word: "fairly", pos: "adv.", cn: "公正地，相当地", freq: 39, example: "The test was fairly easy."},
    {id: 143, word: "regret", pos: "v./n.", cn: "后悔", freq: 39, example: "I regret my decision."},
    {id: 144, word: "strict", pos: "adj.", cn: "严格的(with)", freq: 39, example: "Our teacher is very strict."},
    {id: 145, word: "fellow", pos: "n.", cn: "同事，家伙", freq: 39, example: "He's a nice fellow."},
    {id: 146, word: "gradually", pos: "adv.", cn: "逐渐地", freq: 39, example: "Things gradually improved."},
    {id: 147, word: "belief", pos: "n.", cn: "信念，信仰", freq: 39, example: "Have belief in yourself."},
    {id: 148, word: "imagination", pos: "n.", cn: "想象力", freq: 39, example: "Use your imagination."},
    {id: 149, word: "official", pos: "adj.", cn: "正式的；官方的", freq: 39, example: "This is an official document."},
    {id: 150, word: "account", pos: "n./v.", cn: "帐户，事情；说明(for)", freq: 38, example: "Open a bank account."},

    // 151-200
    {id: 151, word: "persuade", pos: "v.", cn: "说服", freq: 38, example: "I couldn't persuade him."},
    {id: 152, word: "figure", pos: "n./v.", cn: "人物；算出，领会(out)", freq: 38, example: "Can you figure this out?"},
    {id: 153, word: "seldom", pos: "adv.", cn: "很少", freq: 38, example: "I seldom watch TV."},
    {id: 154, word: "eager", pos: "adj.", cn: "渴望的(to)", freq: 38, example: "She's eager to learn."},
    {id: 155, word: "recommend", pos: "v.", cn: "推荐，建议", freq: 37, example: "I recommend this book."},
    {id: 156, word: "remove", pos: "v.", cn: "移除", freq: 37, example: "Remove your shoes, please."},
    {id: 157, word: "unique", pos: "adj.", cn: "唯一的", freq: 37, example: "Everyone is unique."},
    {id: 158, word: "risk", pos: "v./n.", cn: "冒...的危险(of)；危险，风险", freq: 37, example: "Don't take unnecessary risks."},
    {id: 159, word: "economic", pos: "adj.", cn: "经济的", freq: 37, example: "Economic growth is slowing."},
    {id: 160, word: "pollution", pos: "n.", cn: "污染", freq: 36, example: "Air pollution is a serious problem."},
    {id: 161, word: "literature", pos: "n.", cn: "文学", freq: 36, example: "She studies English literature."},
    {id: 162, word: "consume", pos: "v.", cn: "消耗，消费", freq: 36, example: "Don't consume too much sugar."},
    {id: 163, word: "stick", pos: "v.", cn: "粘住，坚持(to)", freq: 36, example: "Stick to your plan."},
    {id: 164, word: "devote", pos: "v.", cn: "致力于(to)", freq: 36, example: "She devotes herself to teaching."},
    {id: 165, word: "predict", pos: "v.", cn: "预言", freq: 35, example: "It's hard to predict the future."},
    {id: 166, word: "complain", pos: "v.", cn: "抱怨(to/about)", freq: 35, example: "Stop complaining!"},
    {id: 167, word: "annoy", pos: "v.", cn: "使恼怒", freq: 35, example: "His behavior annoys me."},
    {id: 168, word: "apply", pos: "v.", cn: "应用(to)，申请(for)", freq: 35, example: "Apply for the job online."},
    {id: 169, word: "handle", pos: "v.", cn: "处理", freq: 35, example: "How do you handle stress?"},
    {id: 170, word: "object", pos: "v./n.", cn: "反对(to)；目标，物体", freq: 35, example: "I object to this plan."},
    {id: 171, word: "select", pos: "v.", cn: "挑选", freq: 35, example: "Select the best option."},
    {id: 172, word: "opposite", pos: "adj.", cn: "相反的，对面的", freq: 35, example: "They have opposite views."},
    {id: 173, word: "solution", pos: "n.", cn: "解决办法", freq: 35, example: "Find a solution to the problem."},
    {id: 174, word: "struggle", pos: "n./v.", cn: "斗争，挣扎(against)", freq: 34, example: "Life is a struggle."},
    {id: 175, word: "approach", pos: "v./n.", cn: "靠近；途径，方法(to)", freq: 34, example: "We need a new approach."},
    {id: 176, word: "urgent", pos: "adj.", cn: "紧急的", freq: 34, example: "This is urgent!"},
    {id: 177, word: "delight", pos: "n.", cn: "高兴", freq: 34, example: "To my delight, we won."},
    {id: 178, word: "talent", pos: "n.", cn: "天赋，才华", freq: 33, example: "She has a talent for music."},
    {id: 179, word: "track", pos: "v./n.", cn: "跟踪；小路", freq: 33, example: "Keep track of your expenses."},
    {id: 180, word: "arrange", pos: "v.", cn: "安排", freq: 33, example: "Arrange the books on the shelf."},
    {id: 181, word: "wealth", pos: "n.", cn: "财富", freq: 33, example: "Health is better than wealth."},
    {id: 182, word: "security", pos: "n.", cn: "安全", freq: 33, example: "Security is tight at the airport."},
    {id: 183, word: "entire", pos: "adj.", cn: "全部的", freq: 32, example: "The entire class passed."},
    {id: 184, word: "positive", pos: "adj.", cn: "积极的", freq: 32, example: "Stay positive!"},
    {id: 185, word: "rarely", pos: "adv.", cn: "很少", freq: 32, example: "I rarely eat meat."},
    {id: 186, word: "reflect", pos: "v.", cn: "反射，反映", freq: 32, example: "His work reflects his personality."},
    {id: 187, word: "contact", pos: "v./n.", cn: "接触，联系(with)", freq: 32, example: "Keep in contact with friends."},
    {id: 188, word: "hesitate", pos: "v.", cn: "犹豫", freq: 32, example: "Don't hesitate to ask."},
    {id: 189, word: "permit", pos: "v.", cn: "允许", freq: 31, example: "Smoking is not permitted."},
    {id: 190, word: "rapid", pos: "adj.", cn: "迅速的", freq: 30, example: "Rapid changes are happening."},
    {id: 191, word: "colleague", pos: "n.", cn: "同事", freq: 30, example: "She's my colleague."},
    {id: 192, word: "conclude", pos: "v.", cn: "总结", freq: 30, example: "To conclude, I agree."},
    {id: 193, word: "host", pos: "n./v.", cn: "主人，主持人；主办，主持", freq: 30, example: "Who will host the party?"},
    {id: 194, word: "version", pos: "n.", cn: "版本", freq: 30, example: "Download the latest version."},
    {id: 195, word: "accommodation", pos: "n.", cn: "住处，适应", freq: 29, example: "Book accommodation early."},
    {id: 196, word: "possess", pos: "v.", cn: "拥有", freq: 29, example: "He possesses great wealth."},
    {id: 197, word: "collection", pos: "n.", cn: "收集", freq: 29, example: "She has a stamp collection."},
    {id: 198, word: "survive", pos: "v.", cn: "幸存", freq: 29, example: "Only the strong survive."},
    {id: 199, word: "feature", pos: "n.", cn: "特征", freq: 29, example: "Safety is a key feature."},
    {id: 200, word: "appreciate", pos: "v.", cn: "欣赏，感激", freq: 29, example: "I appreciate your help."},

    // 201-250
    {id: 201, word: "embarrass", pos: "v.", cn: "使尴尬", freq: 29, example: "Don't embarrass me."},
    {id: 202, word: "profit", pos: "n./v.", cn: "利润，利益；获利", freq: 28, example: "The company made a profit."},
    {id: 203, word: "ancient", pos: "adj.", cn: "古老的", freq: 28, example: "Ancient civilizations."},
    {id: 204, word: "historical", pos: "adj.", cn: "历史的", freq: 28, example: "A historical moment."},
    {id: 205, word: "victim", pos: "n.", cn: "受害者", freq: 28, example: "Help the victims."},
    {id: 206, word: "broaden", pos: "v.", cn: "变宽，扩大", freq: 28, example: "Travel broadens the mind."},
    {id: 207, word: "plastic", pos: "n./adj.", cn: "塑料；可塑的", freq: 27, example: "Reduce plastic use."},
    {id: 208, word: "primary", pos: "adj.", cn: "主要的；首要的，初级的", freq: 27, example: "Primary education is important."},
    {id: 209, word: "reaction", pos: "n.", cn: "反应(to)", freq: 27, example: "What was his reaction?"},
    {id: 210, word: "represent", pos: "v.", cn: "展示，代表", freq: 27, example: "Who will represent us?"},
    {id: 211, word: "response", pos: "n.", cn: "反应，响应(to)", freq: 27, example: "We're waiting for a response."},
    {id: 212, word: "surround", pos: "v.", cn: "包围", freq: 27, example: "Mountains surround the city."},
    {id: 213, word: "average", pos: "adj.", cn: "平均的", freq: 27, example: "The average temperature."},
    {id: 214, word: "smooth", pos: "v./adj.", cn: "使顺利，使光滑；顺利的，光滑的", freq: 27, example: "A smooth surface."},
    {id: 215, word: "cast", pos: "v.", cn: "投射，掷", freq: 26, example: "Cast a shadow."},
    {id: 216, word: "chemical", pos: "adj./n.", cn: "化学的；药品", freq: 26, example: "Chemical reactions."},
    {id: 217, word: "prison", pos: "n.", cn: "监狱", freq: 26, example: "He's in prison."},
    {id: 218, word: "purchase", pos: "v./n.", cn: "购买", freq: 26, example: "Purchase a ticket."},
    {id: 219, word: "straight", pos: "adj.", cn: "直的，直接的", freq: 26, example: "Draw a straight line."},
    {id: 220, word: "switch", pos: "v.", cn: "转换(on)", freq: 26, example: "Switch on the light."},
    {id: 221, word: "treatment", pos: "n.", cn: "对待，治疗", freq: 26, example: "Medical treatment is expensive."},
    {id: 222, word: "aware", pos: "adj.", cn: "意识到的(of)", freq: 26, example: "Be aware of the danger."},
    {id: 223, word: "narrow", pos: "v./adj.", cn: "(使)变窄；狭窄的", freq: 26, example: "A narrow street."},
    {id: 224, word: "hire", pos: "v.", cn: "雇请", freq: 26, example: "We need to hire more staff."},
    {id: 225, word: "shoulder", pos: "n./v.", cn: "肩膀；肩负", freq: 26, example: "Shoulder the responsibility."},
    {id: 226, word: "content", pos: "n./adj.", cn: "内容，目录；满意的(with)", freq: 25, example: "Are you content with your life?"},
    {id: 227, word: "contribute", pos: "v.", cn: "贡献，致力于(to)", freq: 25, example: "Everyone should contribute."},
    {id: 228, word: "concept", pos: "n.", cn: "概念", freq: 25, example: "A new concept."},
    {id: 229, word: "concert", pos: "n.", cn: "音乐会", freq: 25, example: "Go to a concert."},
    {id: 230, word: "conflict", pos: "n.", cn: "冲突", freq: 25, example: "Avoid conflict."},
    {id: 231, word: "decade", pos: "n.", cn: "十年", freq: 25, example: "Over the past decade."},
    {id: 232, word: "sincere", pos: "adj.", cn: "真诚的", freq: 25, example: "Be sincere."},
    {id: 233, word: "release", pos: "v./n.", cn: "释放", freq: 24, example: "Release the pressure."},
    {id: 234, word: "constant", pos: "adj.", cn: "持续不断的", freq: 24, example: "Constant practice."},
    {id: 235, word: "conduct", pos: "v.", cn: "实施", freq: 24, example: "Conduct an experiment."},
    {id: 236, word: "overcome", pos: "v.", cn: "战胜，克服", freq: 24, example: "Overcome difficulties."},
    {id: 237, word: "recycle", pos: "v.", cn: "循环", freq: 23, example: "Recycle plastic bottles."},
    {id: 238, word: "translate", pos: "v.", cn: "翻译", freq: 23, example: "Translate this sentence."},
    {id: 239, word: "fond", pos: "adj.", cn: "喜欢的(of)", freq: 23, example: "I'm fond of reading."},
    {id: 240, word: "grateful", pos: "adj.", cn: "感激的(to)", freq: 23, example: "I'm grateful for your help."},
    {id: 241, word: "guard", pos: "v./n.", cn: "保卫；看守", freq: 23, example: "Guard the entrance."},
    {id: 242, word: "motivate", pos: "v.", cn: "激发", freq: 23, example: "What motivates you?"},
    {id: 243, word: "pause", pos: "v./n.", cn: "停顿；暂停", freq: 22, example: "Pause for a moment."},
    {id: 244, word: "celebrate", pos: "v.", cn: "庆祝", freq: 22, example: "Celebrate your success."},
    {id: 245, word: "trick", pos: "v./n.", cn: "欺骗；诡计", freq: 22, example: "Don't trick me."},
    {id: 246, word: "anxiety", pos: "n.", cn: "焦虑", freq: 22, example: "Reduce anxiety."},
    {id: 247, word: "debate", pos: "v./n.", cn: "辩论", freq: 22, example: "Join the debate."},
    {id: 248, word: "delay", pos: "v./n.", cn: "推迟；耽搁", freq: 22, example: "Don't delay."},
    {id: 249, word: "deserve", pos: "v.", cn: "值得", freq: 22, example: "You deserve better."},
    {id: 250, word: "schedule", pos: "n./v.", cn: "时间表；安排，预定", freq: 22, example: "Check your schedule."},

    // 251-300
    {id: 251, word: "specific", pos: "adj.", cn: "特定的，具体的", freq: 22, example: "Be more specific."},
    {id: 252, word: "concentrate", pos: "v.", cn: "专心，集中(on)", freq: 21, example: "Concentrate on your work."},
    {id: 253, word: "quit", pos: "v.", cn: "停止，放弃", freq: 21, example: "Never quit."},
    {id: 254, word: "stare", pos: "v.", cn: "凝视(at)", freq: 21, example: "Don't stare at people."},
    {id: 255, word: "sympathy", pos: "n.", cn: "同情", freq: 21, example: "Show sympathy."},
    {id: 256, word: "alternative", pos: "adj./n.", cn: "供选择的；替换物", freq: 21, example: "Find an alternative."},
    {id: 257, word: "analyze", pos: "v.", cn: "分析", freq: 21, example: "Analyze the data."},
    {id: 258, word: "ancestor", pos: "n.", cn: "祖宗", freq: 21, example: "Our ancestors."},
    {id: 259, word: "aspect", pos: "n.", cn: "方面", freq: 21, example: "Every aspect of life."},
    {id: 260, word: "disability", pos: "n.", cn: "残疾", freq: 21, example: "People with disabilities."},
    {id: 261, word: "admire", pos: "v.", cn: "钦佩，羡慕", freq: 20, example: "I admire your courage."},
    {id: 262, word: "adolescent", pos: "adj./n.", cn: "青春期的；青少年", freq: 20, example: "Adolescent problems."},
    {id: 263, word: "faithfully", pos: "adv.", cn: "忠实地", freq: 20, example: "Yours faithfully."},
    {id: 264, word: "previous", pos: "adj.", cn: "以前的", freq: 20, example: "Previous experience."},
    {id: 265, word: "reliable", pos: "adj.", cn: "可靠的", freq: 20, example: "A reliable friend."},
    {id: 266, word: "legal", pos: "adj.", cn: "合法的，法律的", freq: 20, example: "Legal advice."},
    {id: 267, word: "compete", pos: "v.", cn: "比赛(with/for/against)", freq: 20, example: "Compete fairly."},
    {id: 268, word: "symbol", pos: "n.", cn: "象征", freq: 20, example: "A symbol of peace."},
    {id: 269, word: "trap", pos: "n.", cn: "陷阱", freq: 20, example: "Fall into a trap."},
    {id: 270, word: "apologize", pos: "v.", cn: "道歉(to sb for sth)", freq: 20, example: "I apologize for being late."},
    {id: 271, word: "mistaken", pos: "adj.", cn: "错误的", freq: 20, example: "You're mistaken."},
    {id: 272, word: "vehicle", pos: "n.", cn: "车辆，交通工具", freq: 20, example: "Motor vehicles."},
    {id: 273, word: "brief", pos: "adj.", cn: "短暂的，简短的", freq: 20, example: "A brief introduction."},
    {id: 274, word: "sharp", pos: "adj.", cn: "急剧的，锋利的，灵敏的", freq: 20, example: "A sharp knife."},
    {id: 275, word: "ordinary", pos: "adj.", cn: "平凡的，普通的", freq: 20, example: "An ordinary day."},
    {id: 276, word: "absorb", pos: "v.", cn: "吸收，吸引", freq: 19, example: "Plants absorb water."},
    {id: 277, word: "ceremony", pos: "n.", cn: "典礼", freq: 19, example: "Wedding ceremony."},
    {id: 278, word: "maintain", pos: "v.", cn: "维持", freq: 19, example: "Maintain good health."},
    {id: 279, word: "consequence", pos: "n.", cn: "后果", freq: 19, example: "Face the consequences."},
    {id: 280, word: "citizen", pos: "n.", cn: "市民", freq: 19, example: "Good citizens."},
    {id: 281, word: "violence", pos: "n.", cn: "暴力", freq: 19, example: "Stop violence."},
    {id: 282, word: "bid", pos: "v.", cn: "出价，投标", freq: 19, example: "Bid for the project."},
    {id: 283, word: "bitter", pos: "adj.", cn: "苦的，痛苦的", freq: 19, example: "Bitter medicine."},
    {id: 284, word: "shame", pos: "n.", cn: "羞愧", freq: 19, example: "What a shame!"},
    {id: 285, word: "bury", pos: "v.", cn: "埋葬", freq: 19, example: "Bury the past."},
    {id: 286, word: "accurate", pos: "adj.", cn: "精确的", freq: 18, example: "Accurate information."},
    {id: 287, word: "adapt", pos: "v.", cn: "适应(to)，改编", freq: 18, example: "Adapt to change."},
    {id: 288, word: "regardless", pos: "adv.", cn: "不顾(of)", freq: 18, example: "Regardless of the cost."},
    {id: 289, word: "commercial", pos: "adj.", cn: "商业的", freq: 18, example: "Commercial success."},
    {id: 290, word: "confidence", pos: "n.", cn: "信心", freq: 18, example: "Build confidence."},
    {id: 291, word: "amaze", pos: "v.", cn: "使吃惊", freq: 18, example: "You amaze me."},
    {id: 292, word: "amuse", pos: "v.", cn: "娱乐", freq: 18, example: "The joke amused everyone."},
    {id: 293, word: "attach", pos: "v.", cn: "附上，系上(to)", freq: 18, example: "Attach the file."},
    {id: 294, word: "typical", pos: "adj.", cn: "特有的，典型的", freq: 18, example: "A typical example."},
    {id: 295, word: "negative", pos: "adj.", cn: "消极的，负面的", freq: 18, example: "Negative attitude."},
    {id: 296, word: "species", pos: "n.", cn: "种类，(单复同)物种", freq: 18, example: "Endangered species."},
    {id: 297, word: "occasion", pos: "n.", cn: "场合，时机", freq: 18, example: "Special occasion."},
    {id: 298, word: "cautious", pos: "adj.", cn: "谨慎的，小心的", freq: 17, example: "Be cautious."},
    {id: 299, word: "engage", pos: "v.", cn: "从事(in)，订婚", freq: 17, example: "Engage in sports."},
    {id: 300, word: "expose", pos: "v.", cn: "揭露，暴露(to)", freq: 17, example: "Expose the truth."},

    // 301-350
    {id: 301, word: "political", pos: "adj.", cn: "政治的", freq: 17, example: "Political issues."},
    {id: 302, word: "convenient", pos: "adj.", cn: "方便的", freq: 17, example: "It's very convenient."},
    {id: 303, word: "assess", pos: "v.", cn: "评定，评估", freq: 17, example: "Assess the situation."},
    {id: 304, word: "astonish", pos: "v.", cn: "使惊讶", freq: 17, example: "The news astonished me."},
    {id: 305, word: "guarantee", pos: "v./n.", cn: "保证", freq: 17, example: "Quality guarantee."},
    {id: 306, word: "decline", pos: "v./n.", cn: "下降，拒绝；衰落", freq: 17, example: "Decline the offer."},
    {id: 307, word: "background", pos: "n.", cn: "背景", freq: 17, example: "Family background."},
    {id: 308, word: "mysterious", pos: "adj.", cn: "神秘的", freq: 17, example: "A mysterious person."},
    {id: 309, word: "block", pos: "n./v.", cn: "街区；阻塞", freq: 17, example: "Block the way."},
    {id: 310, word: "emergency", pos: "n.", cn: "突发事件", freq: 17, example: "Emergency exit."},
    {id: 311, word: "sink", pos: "v.", cn: "下沉(into)", freq: 17, example: "The ship is sinking."},
    {id: 312, word: "abandon", pos: "v.", cn: "放弃，抛弃", freq: 16, example: "Never abandon hope."},
    {id: 313, word: "adjust", pos: "v.", cn: "调节，使适应(to)", freq: 16, example: "Adjust the temperature."},
    {id: 314, word: "capital", pos: "n./adj.", cn: "首都，资本；大写的，资本的", freq: 16, example: "Capital letters."},
    {id: 315, word: "charm", pos: "n.", cn: "魅力", freq: 16, example: "Personal charm."},
    {id: 316, word: "evaluate", pos: "v.", cn: "评价", freq: 16, example: "Evaluate the results."},
    {id: 317, word: "exploit", pos: "v.", cn: "利用，开发", freq: 16, example: "Exploit resources."},
    {id: 318, word: "poison", pos: "v.", cn: "毒害", freq: 16, example: "Poison the mind."},
    {id: 319, word: "migrate", pos: "v.", cn: "迁移，迁徙", freq: 16, example: "Birds migrate south."},
    {id: 320, word: "current", pos: "adj.", cn: "现在的", freq: 16, example: "Current situation."},
    {id: 321, word: "combine", pos: "v.", cn: "结合(with)", freq: 16, example: "Combine work with pleasure."},
    {id: 322, word: "sweep", pos: "v.", cn: "打扫，席卷", freq: 16, example: "Sweep the floor."},
    {id: 323, word: "trade", pos: "n.", cn: "贸易", freq: 16, example: "International trade."},
    {id: 324, word: "appointment", pos: "n.", cn: "约会", freq: 16, example: "Make an appointment."},
    {id: 325, word: "guilty", pos: "adj.", cn: "内疚的(of)，有罪的", freq: 16, example: "Feel guilty."},
    {id: 326, word: "moral", pos: "adj.", cn: "道德的", freq: 16, example: "Moral values."},
    {id: 327, word: "wander", pos: "v.", cn: "漫步，闲逛", freq: 16, example: "Wander around."},
    {id: 328, word: "charity", pos: "n.", cn: "慈善", freq: 15, example: "Charity work."},
    {id: 329, word: "jog", pos: "v.", cn: "慢跑", freq: 15, example: "Jog every morning."},
    {id: 330, word: "ensure", pos: "v.", cn: "确保", freq: 15, example: "Ensure safety."},
    {id: 331, word: "poverty", pos: "n.", cn: "贫困", freq: 15, example: "Fight poverty."},
    {id: 332, word: "precise", pos: "adj.", cn: "精确的", freq: 15, example: "Precise measurements."},
    {id: 333, word: "conservation", pos: "n.", cn: "保护，保存", freq: 15, example: "Wildlife conservation."},
    {id: 334, word: "consult", pos: "v.", cn: "咨询，请教", freq: 15, example: "Consult a doctor."},
    {id: 335, word: "crime", pos: "n.", cn: "罪行", freq: 15, example: "Fight crime."},
    {id: 336, word: "complex", pos: "adj.", cn: "复杂的", freq: 15, example: "Complex problem."},
    {id: 337, word: "forbid", pos: "v.", cn: "禁止", freq: 15, example: "Smoking is forbidden."},
    {id: 338, word: "federal", pos: "adj.", cn: "联邦的", freq: 15, example: "Federal government."},
    {id: 339, word: "gap", pos: "n.", cn: "缺口，差距", freq: 15, example: "Generation gap."},
    {id: 340, word: "apparent", pos: "adj.", cn: "明显的", freq: 15, example: "It's apparent that..."},
    {id: 341, word: "unexpected", pos: "adj.", cn: "想不到的，意外的", freq: 15, example: "Unexpected result."},
    {id: 342, word: "unwilling", pos: "adj.", cn: "不愿意的", freq: 15, example: "Unwilling to help."},
    {id: 343, word: "habitat", pos: "n.", cn: "栖息地，产地", freq: 15, example: "Natural habitat."},
    {id: 344, word: "retire", pos: "v./n.", cn: "退休", freq: 15, example: "Retire at 65."},
    {id: 345, word: "defend", pos: "v.", cn: "保卫，辩护", freq: 15, example: "Defend your rights."},
    {id: 346, word: "withdraw", pos: "v.", cn: "撤回，取回", freq: 15, example: "Withdraw money."},
    {id: 347, word: "participate", pos: "v.", cn: "参加，参与(in)", freq: 15, example: "Participate actively."},
    {id: 348, word: "enable", pos: "v.", cn: "使能够", freq: 15, example: "Enable students to learn."},
    {id: 349, word: "accompany", pos: "v.", cn: "陪伴", freq: 14, example: "Accompany me."},
    {id: 350, word: "chief", pos: "adj./n.", cn: "主要的，首要的；首领", freq: 14, example: "Chief executive."},

    // 351-400
    {id: 351, word: "explode", pos: "v.", cn: "爆炸", freq: 14, example: "The bomb exploded."},
    {id: 352, word: "precious", pos: "adj.", cn: "珍贵的", freq: 14, example: "Precious time."},
    {id: 353, word: "register", pos: "v.", cn: "注册，登记", freq: 14, example: "Register online."},
    {id: 354, word: "remark", pos: "v./n.", cn: "评论", freq: 14, example: "Make a remark."},
    {id: 355, word: "curiosity", pos: "n.", cn: "好奇心", freq: 14, example: "Satisfy your curiosity."},
    {id: 356, word: "theory", pos: "n.", cn: "理论", freq: 14, example: "In theory."},
    {id: 357, word: "thick", pos: "adj.", cn: "厚的", freq: 14, example: "Thick book."},
    {id: 358, word: "affordable", pos: "adj.", cn: "支付得起的", freq: 14, example: "Affordable prices."},
    {id: 359, word: "atmosphere", pos: "n.", cn: "大气，氛围", freq: 14, example: "Friendly atmosphere."},
    {id: 360, word: "household", pos: "n.", cn: "家庭", freq: 14, example: "Household items."},
    {id: 361, word: "humo(u)r", pos: "n.", cn: "幽默", freq: 14, example: "Sense of humor."},
    {id: 362, word: "whisper", pos: "v.", cn: "耳语，私语", freq: 14, example: "Whisper softly."},
    {id: 363, word: "wipe", pos: "v.", cn: "擦", freq: 14, example: "Wipe the table."},
    {id: 364, word: "optimistic", pos: "adj.", cn: "乐观的", freq: 14, example: "Stay optimistic."},
    {id: 365, word: "significant", pos: "adj.", cn: "重要的", freq: 14, example: "Significant change."},
    {id: 366, word: "region", pos: "n.", cn: "地区，范围", freq: 14, example: "Mountain region."},
    {id: 367, word: "addiction", pos: "n.", cn: "上瘾(to)", freq: 13, example: "Internet addiction."},
    {id: 368, word: "facility", pos: "n.", cn: "设施", freq: 13, example: "Sports facilities."},
    {id: 369, word: "recall", pos: "v.", cn: "回忆", freq: 13, example: "I can't recall."},
    {id: 370, word: "remote", pos: "adj.", cn: "偏远的", freq: 13, example: "Remote area."},
    {id: 371, word: "resist", pos: "v.", cn: "抵制，抵抗", freq: 13, example: "Resist temptation."},
    {id: 372, word: "tax", pos: "n.", cn: "税", freq: 13, example: "Pay taxes."},
    {id: 373, word: "fascinate", pos: "v.", cn: "使入迷", freq: 13, example: "Science fascinates me."},
    {id: 374, word: "ambition", pos: "n.", cn: "雄心", freq: 13, example: "Great ambition."},
    {id: 375, word: "appeal", pos: "n./v.", cn: "呼吁；吸引，呼吁(to)", freq: 13, example: "Appeal for help."},
    {id: 376, word: "associate", pos: "v.", cn: "联系(with)", freq: 13, example: "Associate with success."},
    {id: 377, word: "declare", pos: "v.", cn: "声明", freq: 13, example: "Declare war."},
    {id: 378, word: "minor", pos: "adj.", cn: "较小的，次要的", freq: 13, example: "Minor problem."},
    {id: 379, word: "severe", pos: "adj.", cn: "严重的", freq: 13, example: "Severe weather."},
    {id: 380, word: "slip", pos: "v.", cn: "滑倒，溜走", freq: 13, example: "Don't slip."},

    // 381-430
    {id: 381, word: "academic", pos: "adj./n.", cn: "学术的；教授", freq: 12, example: "Academic research."},
    {id: 382, word: "pile", pos: "n.", cn: "堆，大量", freq: 12, example: "A pile of books."},
    {id: 383, word: "pirate", pos: "n.", cn: "海盗，盗版者", freq: 12, example: "Software pirate."},
    {id: 384, word: "chain", pos: "n.", cn: "链条，一连串", freq: 12, example: "Food chain."},
    {id: 385, word: "essential", pos: "adj.", cn: "本质的", freq: 12, example: "Essential skills."},
    {id: 386, word: "psychology", pos: "n.", cn: "心理，心理学", freq: 12, example: "Study psychology."},
    {id: 387, word: "reserve", pos: "v./n.", cn: "预定，保留；自然保护区", freq: 12, example: "Nature reserve."},
    {id: 388, word: "resort", pos: "n.", cn: "(度假)胜地", freq: 12, example: "Ski resort."},
    {id: 389, word: "consist", pos: "v.", cn: "由...组成(of/in)", freq: 12, example: "Consist of three parts."},
    {id: 390, word: "contest", pos: "n./v.", cn: "竞赛", freq: 12, example: "Writing contest."},
    {id: 391, word: "command", pos: "v.", cn: "命令，获得", freq: 12, example: "Command respect."},
    {id: 392, word: "comprehension", pos: "n.", cn: "理解", freq: 12, example: "Reading comprehension."},
    {id: 393, word: "tough", pos: "adj.", cn: "艰难的，棘手的", freq: 12, example: "Tough decision."},
    {id: 394, word: "trend", pos: "n./v.", cn: "趋势；倾向", freq: 12, example: "Fashion trends."},
    {id: 395, word: "assignment", pos: "n.", cn: "分配，任务", freq: 12, example: "Homework assignment."},
    {id: 396, word: "assistant", pos: "n.", cn: "助手", freq: 12, example: "Teaching assistant."},
    {id: 397, word: "bargain", pos: "n./v.", cn: "便宜货；讨价还价", freq: 12, example: "Good bargain."},
    {id: 398, word: "destination", pos: "n.", cn: "目的地", freq: 12, example: "Travel destination."},
    {id: 399, word: "adopt", pos: "v.", cn: "采用，收养", freq: 11, example: "Adopt a child."},
    {id: 400, word: "cheat", pos: "n./v.", cn: "骗子；欺骗", freq: 11, example: "Don't cheat."},
    {id: 401, word: "cheque", pos: "n.", cn: "支票", freq: 11, example: "Write a cheque."},
    {id: 402, word: "preserve", pos: "v.", cn: "保护，保存", freq: 11, example: "Preserve nature."},
    {id: 403, word: "propose", pos: "v.", cn: "计划，提议，求婚", freq: 11, example: "Propose a solution."},
    {id: 404, word: "manufacture", pos: "n./v.", cn: "制造，制造业", freq: 11, example: "Manufacture cars."},
    {id: 405, word: "crisis", pos: "n.", cn: "危机", freq: 11, example: "Economic crisis."},
    {id: 406, word: "confirm", pos: "v.", cn: "确定", freq: 11, example: "Confirm the booking."},
    {id: 407, word: "foundation", pos: "n.", cn: "基金会，基础", freq: 11, example: "Solid foundation."},
    {id: 408, word: "appropriate", pos: "adj.", cn: "适当的", freq: 11, example: "Appropriate behavior."},
    {id: 409, word: "approve", pos: "v.", cn: "赞同，同意(of)", freq: 11, example: "I approve."},
    {id: 410, word: "astronaut", pos: "n.", cn: "宇航员", freq: 11, example: "Become an astronaut."},
    {id: 411, word: "grant", pos: "v.", cn: "授予，认为", freq: 11, example: "Grant permission."},
    {id: 412, word: "routine", pos: "n./adj.", cn: "例行公事；常规的，例行的", freq: 11, example: "Daily routine."},
    {id: 413, word: "impractical", pos: "adj.", cn: "不切实际的", freq: 11, example: "Impractical idea."},
    {id: 414, word: "distinguish", pos: "v.", cn: "区别(from)", freq: 11, example: "Distinguish right from wrong."},
    {id: 415, word: "vital", pos: "adj.", cn: "至关重要的", freq: 11, example: "Vital information."},
    {id: 416, word: "absence", pos: "n.", cn: "缺乏，缺席", freq: 10, example: "In the absence of evidence."},
    {id: 417, word: "peak", pos: "n.", cn: "山峰，顶端", freq: 10, example: "Mountain peak."},
    {id: 418, word: "temporary", pos: "adj.", cn: "暂时的", freq: 10, example: "Temporary job."},
    {id: 419, word: "architect", pos: "n.", cn: "建筑师", freq: 10, example: "Famous architect."},
    {id: 420, word: "universal", pos: "adj.", cn: "普遍的", freq: 10, example: "Universal truth."},
    {id: 421, word: "grasp", pos: "v./n.", cn: "领会，抓住", freq: 10, example: "Grasp the concept."},
    {id: 422, word: "decrease", pos: "v./n.", cn: "降低", freq: 10, example: "Prices decrease."},
    {id: 423, word: "beneficial", pos: "adj.", cn: "有益的(to)", freq: 10, example: "Beneficial effects."},
    {id: 424, word: "define", pos: "v.", cn: "定义", freq: 10, example: "Define the term."},
    {id: 425, word: "vast", pos: "adj.", cn: "广阔的", freq: 10, example: "Vast ocean."},
    {id: 426, word: "witness", pos: "v./n.", cn: "目击；目击者，证人", freq: 10, example: "Eye witness."},
    {id: 427, word: "wrap", pos: "v.", cn: "包，裹", freq: 10, example: "Wrap the gift."},
    {id: 428, word: "candidate", pos: "n.", cn: "候选人", freq: 10, example: "Job candidate."},
    {id: 429, word: "affair", pos: "n.", cn: "事件", freq: 9, example: "Current affairs."},
    {id: 430, word: "acquire", pos: "v.", cn: "获得，学到", freq: 9, example: "Acquire knowledge."},

    // 431-480
    {id: 431, word: "certificate", pos: "n.", cn: "证书，执照", freq: 9, example: "Birth certificate."},
    {id: 432, word: "champion", pos: "n./v.", cn: "冠军；保卫", freq: 9, example: "World champion."},
    {id: 433, word: "estimate", pos: "v.", cn: "估计", freq: 9, example: "Estimate the cost."},
    {id: 434, word: "exhausted", pos: "adj.", cn: "精疲力竭的", freq: 9, example: "Completely exhausted."},
    {id: 435, word: "refresh", pos: "v.", cn: "恢复精神", freq: 9, example: "Refresh yourself."},
    {id: 436, word: "contract", pos: "n./v.", cn: "合同；订合同", freq: 9, example: "Sign a contract."},
    {id: 437, word: "critical", pos: "adj.", cn: "批评的，决定性的", freq: 9, example: "Critical moment."},
    {id: 438, word: "civil", pos: "adj.", cn: "国内的，公民的", freq: 9, example: "Civil war."},
    {id: 439, word: "compose", pos: "v.", cn: "组成，编排", freq: 9, example: "Compose music."},
    {id: 440, word: "splendid", pos: "adj.", cn: "极好的", freq: 9, example: "Splendid view."},
    {id: 441, word: "strike", pos: "v./n.", cn: "打；罢工", freq: 9, example: "Strike a balance."},
    {id: 442, word: "threaten", pos: "v.", cn: "威胁", freq: 9, example: "Threaten safety."},
    {id: 443, word: "tragedy", pos: "n.", cn: "悲剧", freq: 9, example: "Personal tragedy."},
    {id: 444, word: "transform", pos: "v.", cn: "转换", freq: 9, example: "Transform lives."},
    {id: 445, word: "trial", pos: "v./n.", cn: "试验；审讯", freq: 9, example: "Clinical trial."},
    {id: 446, word: "fantasy", pos: "n.", cn: "幻想", freq: 9, example: "Fantasy world."},
    {id: 447, word: "fetch", pos: "v.", cn: "取来", freq: 9, example: "Fetch water."},
    {id: 448, word: "frequently", pos: "adv.", cn: "频繁地", freq: 9, example: "Frequently asked questions."},
    {id: 449, word: "glance", pos: "v./n.", cn: "扫视(at)；一瞥", freq: 9, example: "At first glance."},
    {id: 450, word: "assume", pos: "v.", cn: "假定，设想", freq: 9, example: "Don't assume."},
    {id: 451, word: "uncertain", pos: "adj.", cn: "不确定的", freq: 9, example: "Uncertain future."},
    {id: 452, word: "urban", pos: "adj.", cn: "城市的", freq: 9, example: "Urban development."},
    {id: 453, word: "harbour", pos: "n.", cn: "港口", freq: 9, example: "Safe harbour."},
    {id: 454, word: "harmony", pos: "n.", cn: "和谐", freq: 9, example: "Live in harmony."},
    {id: 455, word: "identify", pos: "v.", cn: "识别，鉴定", freq: 9, example: "Identify the problem."},
    {id: 456, word: "impact", pos: "n.", cn: "影响", freq: 9, example: "Environmental impact."},
    {id: 457, word: "distinct", pos: "adj.", cn: "不同的", freq: 9, example: "Distinct features."},
    {id: 458, word: "scratch", pos: "v.", cn: "抓", freq: 9, example: "Don't scratch."},
    {id: 459, word: "burst", pos: "v.", cn: "爆发(into/out)，闯入", freq: 9, example: "Burst into tears."},
    {id: 460, word: "cancel", pos: "v.", cn: "取消", freq: 9, example: "Cancel the meeting."},
    {id: 461, word: "skip", pos: "v.", cn: "跳过", freq: 9, example: "Skip breakfast."},
    {id: 462, word: "pedestrian", pos: "n.", cn: "路人", freq: 8, example: "Pedestrian crossing."},
    {id: 463, word: "peer", pos: "n./v.", cn: "同辈；凝视", freq: 8, example: "Peer pressure."},
    {id: 464, word: "casual", pos: "adj.", cn: "不经心的，偶然的", freq: 8, example: "Casual clothes."},
    {id: 465, word: "erupt", pos: "v.", cn: "喷发", freq: 8, example: "Volcano erupted."},
    {id: 466, word: "principle", pos: "n.", cn: "原则", freq: 8, example: "Basic principles."},
    {id: 467, word: "loose", pos: "adj.", cn: "宽松的，松散的", freq: 8, example: "Loose clothes."},
    {id: 468, word: "correspond", pos: "v.", cn: "对应(to)", freq: 8, example: "Correspond with reality."},
    {id: 469, word: "advocate", pos: "v.", cn: "提倡", freq: 8, example: "Advocate peace."},
    {id: 470, word: "ashamed", pos: "adj.", cn: "感到惭愧的(of)", freq: 8, example: "Feel ashamed."},
    {id: 471, word: "automatic", pos: "adj.", cn: "自动的", freq: 8, example: "Automatic door."},
    {id: 472, word: "decorate", pos: "v.", cn: "装饰", freq: 8, example: "Decorate the room."},
    {id: 473, word: "rough", pos: "adj.", cn: "粗糙的，艰难的", freq: 8, example: "Rough surface."},
    {id: 474, word: "honorable", pos: "adj.", cn: "光荣的", freq: 8, example: "Honorable mention."},
    {id: 475, word: "illegal", pos: "adj.", cn: "非法的", freq: 8, example: "Illegal activity."},
    {id: 476, word: "negotiate", pos: "v.", cn: "协商(with)", freq: 8, example: "Negotiate a deal."},
    {id: 477, word: "vivid", pos: "adj.", cn: "生动的", freq: 8, example: "Vivid memory."},
    {id: 478, word: "scan", pos: "v.", cn: "扫描，浏览", freq: 8, example: "Scan the document."},
    {id: 479, word: "sculpture", pos: "n.", cn: "雕塑", freq: 8, example: "Beautiful sculpture."},
    {id: 480, word: "selfish", pos: "adj.", cn: "自私的", freq: 8, example: "Don't be selfish."},

    // 481-530
    {id: 481, word: "burden", pos: "n./v.", cn: "负担；使...负重", freq: 8, example: "Heavy burden."},
    {id: 482, word: "absolute", pos: "adj.", cn: "绝对的，完全的", freq: 7, example: "Absolute truth."},
    {id: 483, word: "accomplish", pos: "v.", cn: "实现，完成", freq: 7, example: "Accomplish goals."},
    {id: 484, word: "accuse", pos: "v.", cn: "控告(of)，指责", freq: 7, example: "Accuse of theft."},
    {id: 485, word: "administration", pos: "n.", cn: "管理，行政", freq: 7, example: "School administration."},
    {id: 486, word: "perception", pos: "n.", cn: "观念，洞察力", freq: 7, example: "Change perception."},
    {id: 487, word: "radiation", pos: "n.", cn: "辐射", freq: 7, example: "Radiation therapy."},
    {id: 488, word: "reject", pos: "v.", cn: "拒绝，排斥", freq: 7, example: "Reject the offer."},
    {id: 489, word: "mild", pos: "adj.", cn: "轻微的，温和的", freq: 7, example: "Mild weather."},
    {id: 490, word: "symptom", pos: "n.", cn: "征兆，症状", freq: 7, example: "Disease symptoms."},
    {id: 491, word: "treasure", pos: "n.", cn: "财富", freq: 7, example: "Hidden treasure."},
    {id: 492, word: "tuition", pos: "n.", cn: "学费", freq: 7, example: "Pay tuition."},
    {id: 493, word: "foster", pos: "v./adj.", cn: "培养；收养的", freq: 7, example: "Foster children."},
    {id: 494, word: "freezing", pos: "adj.", cn: "冰冻的", freq: 7, example: "Freezing cold."},
    {id: 495, word: "annual", pos: "adj.", cn: "每年的", freq: 7, example: "Annual report."},
    {id: 496, word: "antique", pos: "adj./n.", cn: "古老的；古董", freq: 7, example: "Antique furniture."},
    {id: 497, word: "arise", pos: "v.", cn: "出现", freq: 7, example: "Problems arise."},
    {id: 498, word: "unemployment", pos: "n.", cn: "失业", freq: 7, example: "High unemployment."},
    {id: 499, word: "gravity", pos: "n.", cn: "重力", freq: 7, example: "Law of gravity."},
    {id: 500, word: "rural", pos: "adj.", cn: "农村的", freq: 7, example: "Rural areas."},
    {id: 501, word: "scare", pos: "v.", cn: "受惊吓", freq: 7, example: "Don't scare me."},
    {id: 502, word: "murder", pos: "n./v.", cn: "谋杀", freq: 7, example: "Murder mystery."},
    {id: 503, word: "horizon", pos: "n.", cn: "地平线", freq: 7, example: "On the horizon."},
    {id: 504, word: "noble", pos: "adj.", cn: "高贵的，贵族的", freq: 7, example: "Noble cause."},
    {id: 505, word: "desperate", pos: "adj.", cn: "绝望的", freq: 7, example: "Desperate situation."},
    {id: 506, word: "weaken", pos: "v.", cn: "削弱", freq: 7, example: "Weaken the enemy."},
    {id: 507, word: "seize", pos: "v.", cn: "抓住", freq: 7, example: "Seize the opportunity."},
    {id: 508, word: "acknowledge", pos: "v.", cn: "承认", freq: 6, example: "Acknowledge the truth."},
    {id: 509, word: "payment", pos: "n.", cn: "支付，报酬", freq: 6, example: "Monthly payment."},
    {id: 510, word: "priority", pos: "n.", cn: "优先", freq: 6, example: "Top priority."},
    {id: 511, word: "procedure", pos: "n.", cn: "程序", freq: 6, example: "Follow procedure."},
    {id: 512, word: "quote", pos: "n./v.", cn: "引用；引述", freq: 6, example: "Famous quote."},
    {id: 513, word: "luxury", pos: "n.", cn: "豪华，奢侈", freq: 6, example: "Luxury goods."},
    {id: 514, word: "contemporary", pos: "adj.", cn: "当代的", freq: 6, example: "Contemporary art."},
    {id: 515, word: "cooperate", pos: "v.", cn: "合作(with)", freq: 6, example: "Cooperate fully."},
    {id: 516, word: "classify", pos: "v.", cn: "分类", freq: 6, example: "Classify information."},
    {id: 517, word: "tight", pos: "adj.", cn: "紧的", freq: 6, example: "Tight schedule."},
    {id: 518, word: "tropical", pos: "adj.", cn: "热带的", freq: 6, example: "Tropical climate."},
    {id: 519, word: "fierce", pos: "adj.", cn: "强烈的，凶猛的", freq: 6, example: "Fierce competition."},
    {id: 520, word: "flexible", pos: "adj.", cn: "灵活的", freq: 6, example: "Flexible schedule."},
    {id: 521, word: "fortunate", pos: "adj.", cn: "幸运的", freq: 6, example: "Very fortunate."},
    {id: 522, word: "giant", pos: "adj.", cn: "巨大的", freq: 6, example: "Giant step."},
    {id: 523, word: "aggressive", pos: "adj.", cn: "好斗的，上进的", freq: 6, example: "Aggressive behavior."},
    {id: 524, word: "anniversary", pos: "n.", cn: "周年纪念", freq: 6, example: "Wedding anniversary."},
    {id: 525, word: "undoubtedly", pos: "adv.", cn: "无疑地", freq: 6, example: "Undoubtedly true."},
    {id: 526, word: "deed", pos: "n.", cn: "行为", freq: 6, example: "Good deed."},
    {id: 527, word: "barely", pos: "adv.", cn: "几乎不", freq: 6, example: "Barely visible."},
    {id: 528, word: "rival", pos: "n./v.", cn: "对手；竞争", freq: 6, example: "Business rival."},
    {id: 529, word: "salary", pos: "n.", cn: "薪水", freq: 6, example: "High salary."},
    {id: 530, word: "hurricane", pos: "n.", cn: "飓风", freq: 6, example: "Hurricane warning."},

    // 531-580
    {id: 531, word: "demonstrate", pos: "v.", cn: "证明，演示", freq: 6, example: "Demonstrate skills."},
    {id: 532, word: "beneath", pos: "prep.", cn: "在...之下", freq: 6, example: "Beneath the surface."},
    {id: 533, word: "brilliant", pos: "adj.", cn: "卓越的，杰出的", freq: 6, example: "Brilliant idea."},
    {id: 534, word: "shortcoming", pos: "n.", cn: "缺点", freq: 6, example: "Personal shortcomings."},
    {id: 535, word: "optional", pos: "adj.", cn: "任选的", freq: 6, example: "Optional course."},
    {id: 536, word: "paradise", pos: "n.", cn: "天堂", freq: 6, example: "Tropical paradise."},
    {id: 537, word: "emphasis", pos: "n.", cn: "强调(on)，重点", freq: 6, example: "Place emphasis on."},
    {id: 538, word: "calculate", pos: "v.", cn: "计算", freq: 6, example: "Calculate the cost."},
    {id: 539, word: "permanent", pos: "adj.", cn: "永久的", freq: 5, example: "Permanent job."},
    {id: 540, word: "capture", pos: "v.", cn: "捕获，占领", freq: 5, example: "Capture attention."},
    {id: 541, word: "justice", pos: "n.", cn: "正义", freq: 5, example: "Seek justice."},
    {id: 542, word: "keen", pos: "adj.", cn: "热衷的(on)；敏锐的", freq: 5, example: "Keen interest."},
    {id: 543, word: "pure", pos: "adj.", cn: "纯的，纯粹的", freq: 5, example: "Pure water."},
    {id: 544, word: "pursue", pos: "v.", cn: "追求", freq: 5, example: "Pursue dreams."},
    {id: 545, word: "reform", pos: "v./n.", cn: "改革", freq: 5, example: "Educational reform."},
    {id: 546, word: "legend", pos: "n.", cn: "传奇", freq: 5, example: "Living legend."},
    {id: 547, word: "clarify", pos: "v.", cn: "阐明", freq: 5, example: "Clarify the issue."},
    {id: 548, word: "subordinate", pos: "adj.", cn: "下级的，次要的", freq: 5, example: "Subordinate position."},
    {id: 549, word: "swallow", pos: "v.", cn: "吞下", freq: 5, example: "Hard to swallow."},
    {id: 550, word: "transfer", pos: "v.", cn: "转移", freq: 5, example: "Transfer money."},
    {id: 551, word: "trigger", pos: "v.", cn: "触发", freq: 5, example: "Trigger a reaction."},
    {id: 552, word: "fasten", pos: "v.", cn: "使固定，系(to)", freq: 5, example: "Fasten seatbelt."},
    {id: 553, word: "fulfill", pos: "v.", cn: "完成", freq: 5, example: "Fulfill dreams."},
    {id: 554, word: "arrest", pos: "v.", cn: "逮捕", freq: 5, example: "Under arrest."},
    {id: 555, word: "unbelievable", pos: "adj.", cn: "难以置信的", freq: 5, example: "Unbelievable story."},
    {id: 556, word: "unconscious", pos: "adj.", cn: "无知觉(意识)的", freq: 5, example: "Unconscious patient."},
    {id: 557, word: "unforgettable", pos: "adj.", cn: "难忘的", freq: 5, example: "Unforgettable experience."},
    {id: 558, word: "valid", pos: "adj.", cn: "有效的", freq: 5, example: "Valid passport."},
    {id: 559, word: "deadline", pos: "n.", cn: "截止时间", freq: 5, example: "Meet the deadline."},
    {id: 560, word: "restore", pos: "v.", cn: "修复，恢复", freq: 5, example: "Restore order."},
    {id: 561, word: "reveal", pos: "v.", cn: "显示，表明", freq: 5, example: "Reveal the truth."},
    {id: 562, word: "immigrant", pos: "n.", cn: "移民", freq: 5, example: "New immigrants."},
    {id: 563, word: "opponent", pos: "n.", cn: "对手", freq: 5, example: "Political opponent."},
    {id: 564, word: "shrink", pos: "v.", cn: "缩水，收缩", freq: 5, example: "Clothes shrink."},
    {id: 565, word: "skeptical", pos: "adj.", cn: "怀疑的", freq: 5, example: "Remain skeptical."},
    {id: 566, word: "abstract", pos: "adj.", cn: "抽象的，理论的", freq: 4, example: "Abstract concept."},
    {id: 567, word: "abuse", pos: "n./v.", cn: "滥用", freq: 4, example: "Drug abuse."},
    {id: 568, word: "accumulate", pos: "v.", cn: "积累", freq: 4, example: "Accumulate wealth."},
    {id: 569, word: "accustom", pos: "v.", cn: "使习惯(to)", freq: 4, example: "Accustom to change."},
    {id: 570, word: "pesticide", pos: "n.", cn: "杀虫剂", freq: 4, example: "Use pesticide."},
    {id: 571, word: "capability", pos: "n.", cn: "能力", freq: 4, example: "Technical capability."},
    {id: 572, word: "cater", pos: "v.", cn: "迎合(for)", freq: 4, example: "Cater to needs."},
    {id: 573, word: "fancy", pos: "v.", cn: "想象，喜欢", freq: 4, example: "Fancy that!"},
    {id: 574, word: "polish", pos: "v.", cn: "磨光，完善", freq: 4, example: "Polish shoes."},
    {id: 575, word: "portable", pos: "adj.", cn: "手提式的", freq: 4, example: "Portable computer."},
    {id: 576, word: "protest", pos: "v.", cn: "抗议(against)", freq: 4, example: "Protest peacefully."},
    {id: 577, word: "stimulus", pos: "n.", cn: "刺激", freq: 4, example: "Economic stimulus."},
    {id: 578, word: "summarize", pos: "v.", cn: "概述", freq: 4, example: "Summarize the article."},
    {id: 579, word: "superior", pos: "adj.", cn: "上层的，较高的(to)", freq: 4, example: "Superior quality."},
    {id: 580, word: "surgery", pos: "n.", cn: "外科手术", freq: 4, example: "Heart surgery."},

    // 581-630
    {id: 581, word: "thoroughly", pos: "adv.", cn: "彻底地", freq: 4, example: "Clean thoroughly."},
    {id: 582, word: "trail", pos: "n.", cn: "小径", freq: 4, example: "Mountain trail."},
    {id: 583, word: "tremble", pos: "v.", cn: "发抖", freq: 4, example: "Tremble with fear."},
    {id: 584, word: "format", pos: "n./v.", cn: "板式；设计", freq: 4, example: "Document format."},
    {id: 585, word: "fundamental", pos: "adj./n.", cn: "基本的；基础", freq: 4, example: "Fundamental principle."},
    {id: 586, word: "anonymous", pos: "adj.", cn: "匿名的", freq: 4, example: "Anonymous letter."},
    {id: 587, word: "appetite", pos: "n.", cn: "食欲(for)，嗜好", freq: 4, example: "Good appetite."},
    {id: 588, word: "arouse", pos: "v.", cn: "引起", freq: 4, example: "Arouse interest."},
    {id: 589, word: "awful", pos: "adj.", cn: "糟糕的", freq: 4, example: "Awful weather."},
    {id: 590, word: "vain", pos: "adj.", cn: "徒劳的(in ~ 徒劳无功)", freq: 4, example: "In vain."},
    {id: 591, word: "restless", pos: "adj.", cn: "不安的", freq: 4, example: "Restless night."},
    {id: 592, word: "reverse", pos: "v./adj.", cn: "逆转；相反的", freq: 4, example: "Reverse the decision."},
    {id: 593, word: "moderate", pos: "adj.", cn: "适度的", freq: 4, example: "Moderate exercise."},
    {id: 594, word: "offence", pos: "n.", cn: "冒犯，犯罪", freq: 4, example: "Criminal offence."},
    {id: 595, word: "delicate", pos: "adj.", cn: "脆弱的，精细的", freq: 4, example: "Delicate situation."},
    {id: 596, word: "wag", pos: "v./n.", cn: "(狗)摇摆(尾巴)；摇摆", freq: 4, example: "The dog wags its tail."},
    {id: 597, word: "breakthrough", pos: "n.", cn: "突破", freq: 4, example: "Scientific breakthrough."},
    {id: 598, word: "reluctant", pos: "adj.", cn: "不情愿的，勉强的", freq: 4, example: "Reluctant to leave."},
    {id: 599, word: "accent", pos: "n.", cn: "口音，重音", freq: 3, example: "Foreign accent."},
    {id: 600, word: "adequate", pos: "adj.", cn: "足够的", freq: 3, example: "Adequate preparation."},
    {id: 601, word: "pavement", pos: "n.", cn: "人行道", freq: 3, example: "Walk on the pavement."},
    {id: 602, word: "prejudice", pos: "n.", cn: "偏见", freq: 3, example: "Racial prejudice."},
    {id: 603, word: "prosperity", pos: "n.", cn: "繁荣，兴旺", freq: 3, example: "Economic prosperity."},
    {id: 604, word: "resemble", pos: "v.", cn: "与...相似", freq: 3, example: "Resemble each other."},
    {id: 605, word: "resolution", pos: "n.", cn: "解决，决心", freq: 3, example: "New Year's resolution."},
    {id: 606, word: "mature", pos: "adj.", cn: "成熟的", freq: 3, example: "Mature attitude."},
    {id: 607, word: "latter", pos: "adj.", cn: "后者的", freq: 3, example: "The latter option."},
    {id: 608, word: "lean", pos: "v.", cn: "倚，倾斜", freq: 3, example: "Lean against the wall."},
    {id: 609, word: "compound", pos: "n.", cn: "化合物", freq: 3, example: "Chemical compound."},
    {id: 610, word: "tolerate", pos: "v.", cn: "容忍，忍受", freq: 3, example: "Cannot tolerate."},
    {id: 611, word: "transmission", pos: "n.", cn: "传输", freq: 3, example: "Data transmission."},
    {id: 612, word: "approximately", pos: "adv.", cn: "大约地，近似地", freq: 3, example: "Approximately correct."},
    {id: 613, word: "artificial", pos: "adj.", cn: "人造的", freq: 3, example: "Artificial intelligence."},
    {id: 614, word: "athletic", pos: "adj.", cn: "运动的，健壮的", freq: 3, example: "Athletic ability."},
    {id: 615, word: "awkward", pos: "adj.", cn: "尴尬的", freq: 3, example: "Awkward silence."},
    {id: 616, word: "damp", pos: "adj.", cn: "潮湿的", freq: 3, example: "Damp weather."},
    {id: 617, word: "dash", pos: "v./n.", cn: "猛冲", freq: 3, example: "Dash to the door."},
    {id: 618, word: "restrict", pos: "v.", cn: "限制", freq: 3, example: "Restrict access."},
    {id: 619, word: "sacrifice", pos: "v./n.", cn: "牺牲(for)；祭品", freq: 3, example: "Make sacrifices."},
    {id: 620, word: "minimize", pos: "v.", cn: "使减(缩)小到最低", freq: 3, example: "Minimize risk."},
    {id: 621, word: "miracle", pos: "n.", cn: "奇迹", freq: 3, example: "It's a miracle."},
    {id: 622, word: "multiple", pos: "adj.", cn: "多种多样的", freq: 3, example: "Multiple choices."},
    {id: 623, word: "neglect", pos: "v.", cn: "忽视，忽略", freq: 3, example: "Neglect duties."},
    {id: 624, word: "notorious", pos: "adj.", cn: "臭名昭著的", freq: 3, example: "Notorious criminal."},
    {id: 625, word: "degrade", pos: "v.", cn: "降解，退化", freq: 3, example: "Degrade naturally."},
    {id: 626, word: "depart", pos: "v.", cn: "离开，死亡", freq: 3, example: "Depart from tradition."},
    {id: 627, word: "accelerate", pos: "v.", cn: "加速", freq: 2, example: "Accelerate growth."},
    {id: 628, word: "adore", pos: "v.", cn: "爱慕，崇拜", freq: 2, example: "I adore you."},
    {id: 629, word: "perspective", pos: "n.", cn: "看法", freq: 2, example: "Different perspective."},
    {id: 630, word: "category", pos: "n.", cn: "种类", freq: 2, example: "Product category."},

    // 631-688 (最后58个)
    {id: 631, word: "exclude", pos: "v.", cn: "排除", freq: 2, example: "Exclude from list."},
    {id: 632, word: "pregnant", pos: "adj.", cn: "怀孕的", freq: 2, example: "She's pregnant."},
    {id: 633, word: "random", pos: "adj.", cn: "随机的(at ~ 随机地)", freq: 2, example: "Random selection."},
    {id: 634, word: "rebel", pos: "v./n.", cn: "造反；造反者", freq: 2, example: "Rebel against authority."},
    {id: 635, word: "leak", pos: "v.", cn: "渗出，泄露", freq: 2, example: "Information leak."},
    {id: 636, word: "starve", pos: "v.", cn: "挨饿", freq: 2, example: "Starve to death."},
    {id: 637, word: "sting", pos: "v.", cn: "叮", freq: 2, example: "Bee sting."},
    {id: 638, word: "sustainable", pos: "adj.", cn: "可持续的", freq: 2, example: "Sustainable development."},
    {id: 639, word: "temptation", pos: "n.", cn: "诱惑", freq: 2, example: "Resist temptation."},
    {id: 640, word: "tiresome", pos: "adj.", cn: "令人厌倦的", freq: 2, example: "Tiresome work."},
    {id: 641, word: "tourism", pos: "n.", cn: "旅游业", freq: 2, example: "Tourism industry."},
    {id: 642, word: "transition", pos: "n.", cn: "过渡，转变", freq: 2, example: "Smooth transition."},
    {id: 643, word: "allocate", pos: "v.", cn: "分配", freq: 2, example: "Allocate resources."},
    {id: 644, word: "angle", pos: "n.", cn: "角度", freq: 2, example: "Different angle."},
    {id: 645, word: "aptitude", pos: "n.", cn: "潜能", freq: 2, example: "Natural aptitude."},
    {id: 646, word: "assertive", pos: "adj.", cn: "坚定的", freq: 2, example: "Be assertive."},
    {id: 647, word: "attribute", pos: "v./n.", cn: "把...归于(to)；品质", freq: 2, example: "Attribute success to hard work."},
    {id: 648, word: "decisive", pos: "adj.", cn: "决定性的", freq: 2, example: "Decisive moment."},
    {id: 649, word: "retain", pos: "v.", cn: "保持，保留", freq: 2, example: "Retain information."},
    {id: 650, word: "retreat", pos: "n./v.", cn: "减少，撤退", freq: 2, example: "Strategic retreat."},
    {id: 651, word: "miserable", pos: "adj.", cn: "悲惨的", freq: 2, example: "Miserable life."},
    {id: 652, word: "illusion", pos: "n.", cn: "错觉", freq: 2, example: "Optical illusion."},
    {id: 653, word: "numerous", pos: "adj.", cn: "许多的", freq: 2, example: "Numerous occasions."},
    {id: 654, word: "defect", pos: "n.", cn: "缺陷", freq: 2, example: "Birth defect."},
    {id: 655, word: "deliberately", pos: "adv.", cn: "故意地", freq: 2, example: "Deliberately ignore."},
    {id: 656, word: "democratic", pos: "adj.", cn: "民主的", freq: 2, example: "Democratic society."},
    {id: 657, word: "demolition", pos: "n.", cn: "破坏，毁坏", freq: 2, example: "Building demolition."},
    {id: 658, word: "boundary", pos: "n.", cn: "边界，分界线", freq: 2, example: "Cross boundaries."},
    {id: 659, word: "slim", pos: "adj./v.", cn: "苗条的；变苗条", freq: 2, example: "Slim chance."},
    {id: 660, word: "abnormal", pos: "adj.", cn: "不正常的", freq: 1, example: "Abnormal behavior."},
    {id: 661, word: "abundant", pos: "adj.", cn: "丰富的", freq: 1, example: "Abundant resources."},
    {id: 662, word: "persist", pos: "v.", cn: "坚持(in)", freq: 1, example: "Persist in trying."},
    {id: 663, word: "cherish", pos: "v.", cn: "珍爱", freq: 1, example: "Cherish memories."},
    {id: 664, word: "lately", pos: "adv.", cn: "最近", freq: 1, example: "Haven't seen you lately."},
    {id: 665, word: "exclaim", pos: "v.", cn: "呼喊", freq: 1, example: "Exclaim in surprise."},
    {id: 666, word: "lighten", pos: "v.", cn: "照亮", freq: 1, example: "Lighten the mood."},
    {id: 667, word: "conscience", pos: "n.", cn: "良心", freq: 1, example: "Clear conscience."},
    {id: 668, word: "time-consuming", pos: "adj.", cn: "耗费时间的", freq: 1, example: "Time-consuming task."},
    {id: 669, word: "ambiguous", pos: "adj.", cn: "模棱两可的", freq: 1, example: "Ambiguous statement."},
    {id: 670, word: "applause", pos: "n.", cn: "鼓掌", freq: 1, example: "Loud applause."},
    {id: 671, word: "assemble", pos: "v.", cn: "聚集", freq: 1, example: "Assemble the team."},
    {id: 672, word: "attain", pos: "v.", cn: "获得", freq: 1, example: "Attain success."},
    {id: 673, word: "vacant", pos: "adj.", cn: "空的", freq: 1, example: "Vacant position."},
    {id: 674, word: "deceive", pos: "v.", cn: "欺骗", freq: 1, example: "Don't deceive me."},
    {id: 675, word: "bankrupt", pos: "adj.", cn: "破产的", freq: 1, example: "Go bankrupt."},
    {id: 676, word: "restrain", pos: "v.", cn: "抑制", freq: 1, example: "Restrain yourself."},
    {id: 677, word: "resume", pos: "n./v.", cn: "简历；继续", freq: 1, example: "Submit your resume."},
    {id: 678, word: "revenge", pos: "v./n.", cn: "报复", freq: 1, example: "Seek revenge."},
    {id: 679, word: "revive", pos: "v.", cn: "复苏", freq: 1, example: "Revive the economy."},
    {id: 680, word: "modify", pos: "v.", cn: "修饰，更改", freq: 1, example: "Modify the plan."},
    {id: 681, word: "obesity", pos: "n.", cn: "肥胖", freq: 1, example: "Fight obesity."},
    {id: 682, word: "delete", pos: "v.", cn: "删除", freq: 1, example: "Delete the file."},
    {id: 683, word: "volatile", pos: "adj.", cn: "不稳定的，易变的", freq: 1, example: "Volatile market."},
    {id: 684, word: "bound", pos: "adj.", cn: "必定的(to)", freq: 1, example: "Bound to succeed."},
    {id: 685, word: "worthwhile", pos: "adj.", cn: "值得(做)的", freq: 1, example: "Worthwhile effort."},
    {id: 686, word: "overwhelm", pos: "v.", cn: "打击，压倒", freq: 1, example: "Don't feel overwhelmed."},
    {id: 687, word: "simulate", pos: "v.", cn: "假装，模仿", freq: 1, example: "Simulate conditions."},
    {id: 688, word: "simultaneously", pos: "adv.", cn: "同时地", freq: 1, example: "Occur simultaneously."}
];
