registerVocab3500('A', [
  { word: "ability", type: "n.", meaning: "能力；才能" },
  { word: "able", type: "a.", meaning: "能够；有能力的" },
  { word: "about", type: "ad.", meaning: "大约；到处；四处", type2: "prep.", meaning2: "关于；在各处；四处" },
  { word: "above", type: "prep.", meaning: "在……上面", type2: "a.", meaning2: "上面的", type3: "ad.", meaning3: "在……之上" },
  { word: "abroad", type: "ad.", meaning: "到（在）国外" },
  { word: "absence", type: "n.", meaning: "不在，缺席" },
  { word: "absent", type: "a.", meaning: "缺席，不在" },
  { word: "accent", type: "n.", meaning: "口音，音调" },
  { word: "accept", type: "vt.", meaning: "接受" },
  { word: "accident", type: "n.", meaning: "事故，意外的事" },
  { word: "according to", type: "ad.", meaning: "按照，根据" },
  { word: "account", type: "n.", meaning: "账目；描述" },
  { word: "ache", type: "vi.& n.", meaning: "痛，疼痛" },
  { word: "achieve", type: "vt.", meaning: "达到，取得" },
  { word: "across", type: "prep.", meaning: "横过，穿过" },
  { word: "act", type: "n.", meaning: "法令，条例", type2: "v.", meaning2: "（戏）表演，扮演（角色），演出（戏）；行动，做事" },
  { word: "action", type: "n.", meaning: "行动" },
  { word: "active", type: "a.", meaning: "积极的，主动的" },
  { word: "activity", type: "n.", meaning: "活动" },
  { word: "actor", type: "n.", meaning: "男演员" },
  { word: "actress", type: "n.", meaning: "女演员" },
  { word: "actual", type: "a.", meaning: "实际的；现实的" },
  { word: "AD", type: "n.", meaning: "公元" },
  { word: "ad", type: "(缩) =advertisement n.", meaning: "广告" },
  { word: "add", type: "vt.", meaning: "添加，增加" },
  { word: "addition", type: "n.", meaning: "增加；（算数用语）加" },
  { word: "address", type: "n.", meaning: "地址" },
  { word: "admire", type: "v.", meaning: "钦佩；羡慕" },
  { word: "admission", type: "n.", meaning: "准入, 接纳" },
  { word: "admit", type: "vt.", meaning: "承认，准许（入场，入学，入会）" },
  { word: "adult", type: "n.", meaning: "成年人" },
  { word: "advance", type: "v.", meaning: "推进，促进；前进" },
  { word: "advantage", type: "n.", meaning: "优点；好处" },
  { word: "adventure", type: "n.", meaning: "冒险；奇遇" },
  { word: "advertise", type: "vt.", meaning: "为……做广告" },
  { word: "advertisement", type: "n.", meaning: "广告" },
  { word: "advice", type: "n.", meaning: "忠告，劝告，建议" },
  { word: "advise", type: "vt.", meaning: "忠告，劝告，建议" },
  { word: "aeroplane", type: "n.", meaning: "(英)飞机" },
  { word: "affair", type: "n.", meaning: "事，事情" },
  { word: "affect", type: "vt.", meaning: "影响" },
  { word: "afford", type: "vt.", meaning: "负担得起（……的费用）；抽得出（时间）；提供" },
  { word: "afraid", type: "a.", meaning: "害怕的；担心" },
  { word: "Africa", type: "n.", meaning: "非洲", note: "*" },
  { word: "African", type: "a.", meaning: "非洲的，非洲人的", type2: "n.", meaning2: "非洲人" },
  { word: "after", type: "ad.", meaning: "在后；后来", type2: "prep.", meaning2: "在……之后；在后面", type3: "conj.", meaning3: "在……以后" },
  { word: "afternoon", type: "n.", meaning: "下午，午后" },
  { word: "afterwards", type: "ad.", meaning: "后来" },
  { word: "again", type: "ad.", meaning: "再一次；再，又" },
  { word: "against", type: "prep.", meaning: "对着，反对" },
  { word: "age", type: "n.", meaning: "年龄；时代" },
  { word: "aggression", type: "n.", meaning: "侵略" },
  { word: "aggressive", type: "a.", meaning: "侵略的；咄咄逼人的" },
  { word: "ago", type: "ad.", meaning: "以前" },
  { word: "agree", type: "v.", meaning: "同意；应允" },
  { word: "agreement", type: "n.", meaning: "同意，一致；协定，协议" },
  { word: "agricultural", type: "a.", meaning: "农业的" },
  { word: "agriculture", type: "n.", meaning: "农业，农学" },
  { word: "ahead", type: "ad.", meaning: "在前，向前" },
  { word: "aid", type: "n.", meaning: "援助；救护；辅助器具" },
  { word: "AIDS", type: "n.", meaning: "艾滋病" },
  { word: "aim", type: "n.", meaning: "目的；目标", type2: "v.", meaning2: "计划，打算；瞄准；针对" },
  { word: "air", type: "n.", meaning: "空气；大气" },
  { word: "aircraft", type: "n.", meaning: "飞机 (单复数同)" },
  { word: "airline", type: "n.", meaning: "航空公司；航空系统" },
  { word: "airmail", type: "n.", meaning: "航空邮件" },
  { word: "airplane", type: "n.", meaning: "（美）飞机" },
  { word: "airport", type: "n.", meaning: "航空站，飞机场" },
  { word: "alarm", type: "n.", meaning: "警报" },
  { word: "alive", type: "a.", meaning: "活着的，存在的" },
  { word: "all", type: "ad.", meaning: "全部地", type2: "a.", meaning2: "全（部）；所有的；总；整", type3: "pron.", meaning3: "全部；全体人员" },
  { word: "allow", type: "vt.", meaning: "允许，准许" },
  { word: "almost", type: "ad.", meaning: "几乎，差不多" },
  { word: "alone", type: "a.", meaning: "单独的，孤独的" },
  { word: "along", type: "ad.", meaning: "向前；和……一起；一同", type2: "prep.", meaning2: "沿着；顺着" },
  { word: "aloud", type: "ad.", meaning: "大声地" },
  { word: "already", type: "ad.", meaning: "已经" },
  { word: "also", type: "ad.", meaning: "也" },
  { word: "although", type: "conj.", meaning: "虽然，尽管" },
  { word: "altogether", type: "ad.", meaning: "总共" },
  { word: "always", type: "ad.", meaning: "总是；一直；永远" },
  { word: "am", type: "v.", meaning: "be的人称形式之一" },
  { word: "a.m./am，A.M./AM", type: "n.", meaning: "午前，上午" },
  { word: "amaze", type: "v.", meaning: "惊奇，惊叹；震惊" },
  { word: "ambulance", type: "n.", meaning: "救护车" },
  { word: "America", type: "n.", meaning: "美国；美洲", note: "*" },
  { word: "American", type: "a.", meaning: "美国的；美国人的", type2: "n.", meaning2: "美国人" },
  { word: "among", type: "prep.", meaning: "在…中间；在（三个以上）之间" },
  { word: "amuse", type: "vt.", meaning: "（使人）快乐，逗乐" },
  { word: "amusement", type: "n.", meaning: "娱乐" },
  { word: "ancient", type: "a.", meaning: "古代的，古老的" },
  { word: "ancestor", type: "n.", meaning: "祖宗；祖先" },
  { word: "and", type: "conj.", meaning: "和；又；而" },
  { word: "anger", type: "n.", meaning: "怒，愤怒" },
  { word: "angry", type: "a.", meaning: "生气的，愤怒的" },
  { word: "animal", type: "n.", meaning: "动物" },
  { word: "announce", type: "vt.", meaning: "宣布，宣告" },
  { word: "announcement", type: "n.", meaning: "通告，通知" },
  { word: "annoy", type: "vt.", meaning: "（使）烦恼" },
  { word: "another", type: "a.", meaning: "再一；另一；别的；不同的", type2: "pron.", meaning2: "另一个" },
  { word: "answer", type: "n.", meaning: "回答，答复；回信；答案", type2: "v.", meaning2: "回答，答复；回信；（作出）答案" },
  { word: "ant", type: "n.", meaning: "蚂蚁" },
  { word: "Antarctic", type: "a.", meaning: "南极的" },
  { word: "the Antarctic", meaning: "南极" },
  { word: "Antarctica", type: "n.", meaning: "南极洲", note: "*" },
  { word: "antique", type: "n.", meaning: "古董" },
  { word: "anxious", type: "a.", meaning: "忧虑的，焦急的" },
  { word: "any", type: "pron.", meaning: "（无论）哪一个；哪些 任何的；（用于疑问句、否定句）一些；什么" },
  { word: "anybody", type: "pron.", meaning: "任何人，无论谁" },
  { word: "anyhow", type: "ad.", meaning: "不管怎样" },
  { word: "anyone", type: "pron.", meaning: "任何人，无论谁" },
  { word: "anything", type: "pron.", meaning: "什么事（物）；任何事（物）" },
  { word: "anyway", type: "ad.", meaning: "不管怎样" },
  { word: "anywhere", type: "ad.", meaning: "任何地方" },
  { word: "apartment", type: "n.", meaning: "（美）楼中单元房，一套房间；房间" },
  { word: "apologize", type: "vi.", meaning: "道歉，谢罪" },
  { word: "apology", type: "n.", meaning: "道歉；歉意" },
  { word: "appear", type: "vi.", meaning: "出现" },
  { word: "appearance", type: "n.", meaning: "出现，露面；容貌" },
  { word: "apple", type: "n.", meaning: "苹果" },
  { word: "application", type: "n.", meaning: "申请" },
  { word: "apply", type: "v.", meaning: "申请" },
  { word: "appointment", type: "n.", meaning: "约会" },
  { word: "appreciate", type: "v.", meaning: "欣赏；感激" },
  { word: "April", type: "n.", meaning: "4月" },
  { word: "Arab", type: "a.", meaning: "阿拉伯的", type2: "n.", meaning2: "阿拉伯人", note: "*" },
  { word: "Arabic", type: "a.", meaning: "阿拉伯语的", type2: "n.", meaning2: "阿拉伯语" },
  { word: "Arctic", type: "a.", meaning: "北极的" },
  { word: "the Arctic", meaning: "北极" },
  { word: "the Arctic Ocean", meaning: "北冰洋" },
  { word: "area", type: "n.", meaning: "面积；地域，地方，区域；范围，领域" },
  { word: "argue", type: "vi.", meaning: "争辩，争论" },
  { word: "argument", type: "n.", meaning: "争论，辩论" },
  { word: "arise", type: "vi.", meaning: "起来，升起；出现", forms: "(arose, arisen)" },
  { word: "arithmetic", type: "n.", meaning: "算术" },
  { word: "arm", type: "n.", meaning: "臂, 支架", note: "1" },
  { word: "arm", type: "v.", meaning: "以……装备，武装起来", type2: "n.", meaning2: "（美）武器，武力", note: "2" },
  { word: "armchair", type: "n.", meaning: "扶手椅" },
  { word: "army", type: "n.", meaning: "军队" },
  { word: "around", type: "ad.", meaning: "在周围；在附近", type2: "prep.", meaning2: "在……周围；大约" },
  { word: "arrange", type: "v.", meaning: "安排，布置" },
  { word: "arrangement", type: "n.", meaning: "安排，布置" },
  { word: "arrival", type: "n.", meaning: "到来，到达" },
  { word: "arrive", type: "vi.", meaning: "到达；达到" },
  { word: "arrow", type: "n.", meaning: "箭；箭头" },
  { word: "art", type: "n.", meaning: "艺术，美术；技艺" },
  { word: "article", type: "n.", meaning: "文章；东西，物品；冠词" },
  { word: "artist", type: "n.", meaning: "艺术家" },
  { word: "as", type: "ad.& conj.", meaning: "像……一样；如同；因为", type2: "prep.", meaning2: "作为，当做" },
  { word: "ash", type: "n.", meaning: "灰；灰末" },
  { word: "ashamed", type: "a.", meaning: "惭愧；害臊" },
  { word: "Asia", type: "n.", meaning: "亚洲", note: "*" },
  { word: "Asian", type: "a.", meaning: "亚洲的，亚洲人的", type2: "n.", meaning2: "亚洲人" },
  { word: "aside", type: "ad.", meaning: "在旁边" },
  { word: "ask", type: "v.", meaning: "问，询问；请求，要求；邀请" },
  { word: "asleep", type: "a.", meaning: "睡着的，熟睡" },
  { word: "assistant", type: "n.", meaning: "助手，助理" },
  { word: "astonish", type: "vt.", meaning: "使惊讶" },
  { word: "astronaut", type: "n.", meaning: "宇航员" },
  { word: "astronomy", type: "n.", meaning: "天文学" },
  { word: "at", type: "prep.", meaning: "在（几点钟）；在（某处）" },
  { word: "athlete", type: "n.", meaning: "运动员" },
  { word: "Atlantic", type: "a.", meaning: "大西洋的" },
  { word: "the Atlantic Ocean", meaning: "大西洋" },
  { word: "atmosphere", type: "n.", meaning: "大气；气氛" },
  { word: "atom", type: "n.", meaning: "原子，微粒" },
  { word: "attack", type: "vt.", meaning: "攻击，袭击" },
  { word: "attempt", type: "vt.", meaning: "试图，尝试" },
  { word: "attend", type: "v.", meaning: "看护，照料，服侍；出席，参加" },
  { word: "attention", type: "n.", meaning: "注意，关心" },
  { word: "attentively", type: "ad.", meaning: "注意地" },
  { word: "attitude", type: "n.", meaning: "态度，看法" },
  { word: "attract", type: "v.", meaning: "吸引，引起" },
  { word: "attractive", type: "a.", meaning: "迷人的，有吸引力的" },
  { word: "audience", type: "n.", meaning: "观众，听众" },
  { word: "author", type: "n.", meaning: "作者，作家" },
  { word: "August", type: "n.", meaning: "8月" },
  { word: "aunt", type: "n.", meaning: "伯母；舅母；婶；姑；姨" },
  { word: "Australia", type: "n.", meaning: "澳洲；澳大利亚", note: "*" },
  { word: "Australian", type: "a.", meaning: "澳洲的，澳大利亚人的", type2: "n.", meaning2: "澳大利亚人" },
  { word: "autumn", type: "n.", meaning: "秋天，秋季" },
  { word: "avenue", type: "n.", meaning: "大道" },
  { word: "average", type: "a.", meaning: "平均的；普通的", type2: "n.", meaning2: "平均数" },
  { word: "avoid", type: "v.", meaning: "避免，躲开，逃避" },
  { word: "awake", type: "v.", meaning: "唤醒 醒着的", forms: "(awoke, awoken)" },
  { word: "award", type: "n.", meaning: "奖品，奖励" },
  { word: "away", type: "ad.", meaning: "离开；远离" }
]);
