const requiredBook2 = {
  "必修第二册": {
    "Unit 1 Cultural Heritage": {
      "词汇": [
        { "word": "application", "translation": "申请，应用" },
        { "word": "archaeologist", "translation": "考古学家" },
        { "word": "balance", "translation": "平衡，均衡" },
        { "word": "clue", "translation": "线索，提示" },
        { "word": "committee", "translation": "委员会" },
        { "word": "contribution", "translation": "贡献，捐献" },
        { "word": "creative", "translation": "创造性的" },
        { "word": "digital", "translation": "数字的，数码的" },
        { "word": "disappear", "translation": "消失，不见" },
        { "word": "donate", "translation": "捐赠，捐献" },
        { "word": "document", "translation": "文件，文献" },
        { "word": "download", "translation": "下载" },
        { "word": "dragon", "translation": "龙" },
        { "word": "entrance", "translation": "入口，进入" },
        { "word": "establish", "translation": "建立，创立" },
        { "word": "forever", "translation": "永远" },
        { "word": "forgive", "translation": "原谅，宽恕" },
        { "word": "former", "translation": "以前的，前者" },
        { "word": "fund", "translation": "基金，资金" },
        { "word": "heritage", "translation": "遗产" },
        { "word": "historic", "translation": "历史上著名的" },
        { "word": "identify", "translation": "识别，确认" },
        { "word": "image", "translation": "形象，图像" },
        { "word": "issue", "translation": "问题，发行" },
        { "word": "mount", "translation": "山峰，增加" },
        { "word": "opinion", "translation": "意见，看法" },
        { "word": "overseas", "translation": "海外的，国外的" },
        { "word": "parade", "translation": "游行，检阅" },
        { "word": "preserve", "translation": "保护，保存" },
        { "word": "prevent", "translation": "阻止，预防" },
        { "word": "process", "translation": "过程，处理" },
        { "word": "professional", "translation": "专业的，职业的" },
        { "word": "promote", "translation": "促进，提升" },
        { "word": "proposal", "translation": "提议，建议" },
        { "word": "protest", "translation": "抗议，反对" },
        { "word": "quality", "translation": "质量，品质" },
        { "word": "quote", "translation": "引用，引述" },
        { "word": "republic", "translation": "共和国" },
        { "word": "temple", "translation": "寺庙，神殿" },
        { "word": "tradition", "translation": "传统，惯例" },
        { "word": "worthwhile", "translation": "值得的" }
      ],
      "词组": [
        { "phrase": "all over the world", "translation": "全世界" },
        { "phrase": "donate to", "translation": "捐赠给" },
        { "phrase": "give way to", "translation": "让步于，让路给" },
        { "phrase": "keep balance", "translation": "保持平衡" },
        { "phrase": "lead to", "translation": "导致，通向" },
        { "phrase": "make a proposal", "translation": "提出建议" },
        { "phrase": "make sure", "translation": "确保，确定" },
        { "phrase": "prevent from", "translation": "阻止...做" },
        { "phrase": "take part in", "translation": "参加，参与" },
        { "phrase": "turn to", "translation": "转向，求助于" }
      ]
    },
    "Unit 2 Wildlife Protection": {
      "词汇": [
        { "word": "adapt", "translation": "适应，改编" },
        { "word": "alarm", "translation": "警报，惊慌" },
        { "word": "attack", "translation": "攻击，进攻" },
        { "word": "authority", "translation": "权威，当局" },
        { "word": "average", "translation": "平均的，普通的" },
        { "word": "aware", "translation": "意识到的" },
        { "word": "beauty", "translation": "美，美人" },
        { "word": "concern", "translation": "关心，忧虑" },
        { "word": "creature", "translation": "生物，动物" },
        { "word": "dolphin", "translation": "海豚" },
        { "word": "effective", "translation": "有效的" },
        { "word": "emotion", "translation": "情感，情绪" },
        { "word": "endangered", "translation": "濒危的" },
        { "word": "exist", "translation": "存在，生存" },
        { "word": "extinction", "translation": "灭绝，消亡" },
        { "word": "habitat", "translation": "栖息地" },
        { "word": "harmony", "translation": "和谐，协调" },
        { "word": "hunt", "translation": "打猎，搜寻" },
        { "word": "illegal", "translation": "非法的" },
        { "word": "immediately", "translation": "立即，马上" },
        { "word": "intend", "translation": "打算，意图" },
        { "word": "living", "translation": "活的，生活" },
        { "word": "measure", "translation": "措施，测量" },
        { "word": "neighborhood", "translation": "邻近地区" },
        { "word": "observe", "translation": "观察，遵守" },
        { "word": "plain", "translation": "平原，朴素的" },
        { "word": "pressure", "translation": "压力，压迫" },
        { "word": "profit", "translation": "利润，利益" },
        { "word": "rate", "translation": "速度，比率" },
        { "word": "recover", "translation": "恢复，康复" },
        { "word": "reduce", "translation": "减少，降低" },
        { "word": "remind", "translation": "提醒，使想起" },
        { "word": "remove", "translation": "移走，去除" },
        { "word": "reserve", "translation": "保护区，储备" },
        { "word": "search", "translation": "搜索，寻找" },
        { "word": "shoot", "translation": "射击，拍摄" },
        { "word": "species", "translation": "物种，种类" },
        { "word": "threat", "translation": "威胁，恐吓" },
        { "word": "unusual", "translation": "不寻常的" }
      ],
      "词组": [
        { "phrase": "aware of", "translation": "意识到" },
        { "phrase": "be concerned about", "translation": "关心，担心" },
        { "phrase": "die out", "translation": "灭绝，消失" },
        { "phrase": "due to", "translation": "由于，因为" },
        { "phrase": "make out", "translation": "理解，辨认出" },
        { "phrase": "make profits", "translation": "获利，赚钱" },
        { "phrase": "on average", "translation": "平均" },
        { "phrase": "on earth", "translation": "究竟，在世界上" },
        { "phrase": "remind of", "translation": "使想起" },
        { "phrase": "search for", "translation": "搜寻，寻找" },
        { "phrase": "under pressure", "translation": "在压力下" },
        { "phrase": "watch over", "translation": "看守，照看" }
      ]
    },
    "Unit 3 The Internet": {
      "词汇": [
        { "word": "access", "translation": "接近，使用权" },
        { "word": "account", "translation": "账户，描述" },
        { "word": "battery", "translation": "电池" },
        { "word": "benefit", "translation": "利益，好处" },
        { "word": "blog", "translation": "博客" },
        { "word": "case", "translation": "情况，案例" },
        { "word": "cash", "translation": "现金" },
        { "word": "chat", "translation": "聊天，闲谈" },
        { "word": "click", "translation": "点击" },
        { "word": "conference", "translation": "会议，讨论会" },
        { "word": "confirm", "translation": "确认，证实" },
        { "word": "convenient", "translation": "方便的，便利的" },
        { "word": "database", "translation": "数据库" },
        { "word": "define", "translation": "定义，限定" },
        { "word": "discount", "translation": "折扣，打折" },
        { "word": "distance", "translation": "距离，远处" },
        { "word": "download", "translation": "下载" },
        { "word": "function", "translation": "功能，作用" },
        { "word": "identity", "translation": "身份，特性" },
        { "word": "inspire", "translation": "激发，鼓舞" },
        { "word": "network", "translation": "网络，网状系统" },
        { "word": "particular", "translation": "特别的，特定的" },
        { "word": "plus", "translation": "加，加上" },
        { "word": "press", "translation": "按，新闻界" },
        { "word": "privacy", "translation": "隐私，私密" },
        { "word": "province", "translation": "省，领域" },
        { "word": "resident", "translation": "居民，住院医生" },
        { "word": "stream", "translation": "溪流，流动" },
        { "word": "stuck", "translation": "卡住的，困住的" },
        { "word": "surf", "translation": "冲浪，浏览" },
        { "word": "target", "translation": "目标，靶子" },
        { "word": "tough", "translation": "困难的，坚韧的" },
        { "word": "update", "translation": "更新，使现代化" }
      ],
      "词组": [
        { "phrase": "go through", "translation": "经历，检查" },
        { "phrase": "in case", "translation": "以防万一" },
        { "phrase": "keep in mind", "translation": "记住" },
        { "phrase": "keep track of", "translation": "跟踪，记录" },
        { "phrase": "now that", "translation": "既然，由于" },
        { "phrase": "out of work", "translation": "失业" }
      ]
    },
    "Unit 4 History and Traditions": {
      "词汇": [
        { "word": "achieve", "translation": "达到，实现" },
        { "word": "amount", "translation": "数量，总计" },
        { "word": "ancestor", "translation": "祖先，祖宗" },
        { "word": "announce", "translation": "宣布，通告" },
        { "word": "approach", "translation": "接近，方法" },
        { "word": "battle", "translation": "战斗，战役" },
        { "word": "belong", "translation": "属于" },
        { "word": "charge", "translation": "收费，指控" },
        { "word": "chief", "translation": "首领，主要的" },
        { "word": "conquer", "translation": "征服，战胜" },
        { "word": "county", "translation": "郡，县" },
        { "word": "crowd", "translation": "人群，拥挤" },
        { "word": "custom", "translation": "风俗，习惯" },
        { "word": "defend", "translation": "保卫，辩护" },
        { "word": "eager", "translation": "渴望的，热切的" },
        { "word": "ensure", "translation": "确保，保证" },
        { "word": "evidence", "translation": "证据，证明" },
        { "word": "fascinating", "translation": "迷人的，吸引人的" },
        { "word": "gallery", "translation": "画廊，走廊" },
        { "word": "greet", "translation": "问候，迎接" },
        { "word": "individual", "translation": "个人，个体的" },
        { "word": "introduce", "translation": "介绍，引进" },
        { "word": "kingdom", "translation": "王国，领域" },
        { "word": "landscape", "translation": "风景，景色" },
        { "word": "legal", "translation": "法律的，合法的" },
        { "word": "location", "translation": "位置，地点" },
        { "word": "military", "translation": "军事的，军队" },
        { "word": "nearby", "translation": "附近的" },
        { "word": "ocean", "translation": "海洋，大海" },
        { "word": "poet", "translation": "诗人" },
        { "word": "port", "translation": "港口，港" },
        { "word": "position", "translation": "位置，职位" },
        { "word": "pub", "translation": "酒吧，酒馆" },
        { "word": "puzzle", "translation": "谜，使困惑" },
        { "word": "roll", "translation": "滚动，卷" },
        { "word": "scent", "translation": "气味，香味" },
        { "word": "surround", "translation": "包围，围绕" },
        { "word": "tradition", "translation": "传统，惯例" }
      ],
      "词组": [
        { "phrase": "as well as", "translation": "也，和...一样" },
        { "phrase": "belong to", "translation": "属于" },
        { "phrase": "break away from", "translation": "脱离，摆脱" },
        { "phrase": "join to", "translation": "把...连接到" },
        { "phrase": "keep your eyes open", "translation": "留心，注意观察" },
        { "phrase": "result in", "translation": "导致，造成" }
      ]
    },
    "Unit 5 Music": {
      "词汇": [
        { "word": "absorb", "translation": "吸收，使专心" },
        { "word": "aim", "translation": "目标，瞄准" },
        { "word": "altogether", "translation": "完全，总共" },
        { "word": "assume", "translation": "假定，设想" },
        { "word": "award", "translation": "奖，授予" },
        { "word": "capable", "translation": "有能力的" },
        { "word": "classical", "translation": "古典的，经典的" },
        { "word": "composer", "translation": "作曲家" },
        { "word": "cure", "translation": "治愈，疗法" },
        { "word": "disease", "translation": "疾病" },
        { "word": "enable", "translation": "使能够" },
        { "word": "energy", "translation": "能量，精力" },
        { "word": "equipment", "translation": "设备，装备" },
        { "word": "fall", "translation": "落下，下降" },
        { "word": "gradual", "translation": "逐渐的，渐进的" },
        { "word": "impact", "translation": "影响，冲击" },
        { "word": "lean", "translation": "倾斜，瘦的" },
        { "word": "moreover", "translation": "而且，此外" },
        { "word": "opportunity", "translation": "机会，时机" },
        { "word": "ordinary", "translation": "普通的，平常的" },
        { "word": "original", "translation": "原创的，原始的" },
        { "word": "outline", "translation": "大纲，轮廓" },
        { "word": "perform", "translation": "表演，执行" },
        { "word": "phenomenon", "translation": "现象" },
        { "word": "previous", "translation": "以前的，先前的" },
        { "word": "prove", "translation": "证明，证实" },
        { "word": "rap", "translation": "说唱音乐" },
        { "word": "reaction", "translation": "反应，回应" },
        { "word": "relief", "translation": "宽慰，救济" },
        { "word": "repetition", "translation": "重复，反复" },
        { "word": "romantic", "translation": "浪漫的" },
        { "word": "satisfaction", "translation": "满意，满足" },
        { "word": "somehow", "translation": "不知怎地" },
        { "word": "soul", "translation": "灵魂，心灵" },
        { "word": "stage", "translation": "舞台，阶段" },
        { "word": "studio", "translation": "工作室，录音棚" },
        { "word": "thus", "translation": "因此，这样" },
        { "word": "treatment", "translation": "治疗，对待" },
        { "word": "unemployed", "translation": "失业的" },
        { "word": "various", "translation": "各种各样的" },
        { "word": "virtual", "translation": "虚拟的，实质的" }
      ],
      "词组": [
        { "phrase": "absorbed in", "translation": "专心于" },
        { "phrase": "fall in love with", "translation": "爱上" },
        { "phrase": "from then on", "translation": "从那时起" },
        { "phrase": "get through", "translation": "通过，完成" },
        { "phrase": "have an impact on", "translation": "对...有影响" },
        { "phrase": "in addition to", "translation": "除...之外" },
        { "phrase": "set up", "translation": "建立，创立" }
      ]
    }
  }
};

if(typeof window !== "undefined" && typeof window.registerTextbookBook === "function"){
  window.registerTextbookBook("requiredBook2", requiredBook2);
}
