const requiredBook1 = {
  "必修第一册": {
    "Welcome Unit": {
      "词汇": [
        { "word": "ability", "translation": "能力，才能" },
        { "word": "absence", "translation": "缺席，不在" },
        { "word": "absolutely", "translation": "绝对地，完全地" },
        { "word": "academic", "translation": "学术的，学业的" },
        { "word": "accept", "translation": "接受，认可" },
        { "word": "access", "translation": "接近，进入；使用权" },
        { "word": "accident", "translation": "事故，意外" },
        { "word": "achieve", "translation": "达到，实现" },
        { "word": "achievement", "translation": "成就，成绩" },
        { "word": "adapt", "translation": "适应，改编" },
        { "word": "advantage", "translation": "优势，有利条件" },
        { "word": "affect", "translation": "影响，感动" },
        { "word": "afford", "translation": "负担得起，提供" },
        { "word": "although", "translation": "虽然，尽管" },
        { "word": "anxious", "translation": "焦虑的，渴望的" },
        { "word": "apologize", "translation": "道歉，谢罪" },
        { "word": "appreciate", "translation": "欣赏，感激" },
        { "word": "approach", "translation": "接近，方法" },
        { "word": "arrange", "translation": "安排，整理" },
        { "word": "assignment", "translation": "作业，任务" },
        { "word": "atmosphere", "translation": "气氛，大气" },
        { "word": "attitude", "translation": "态度，看法" },
        { "word": "available", "translation": "可获得的，有空的" },
        { "word": "balance", "translation": "平衡，均衡" },
        { "word": "behavior", "translation": "行为，举止" },
        { "word": "benefit", "translation": "利益，好处" },
        { "word": "challenge", "translation": "挑战，质疑" },
        { "word": "comfortable", "translation": "舒适的，安逸的" },
        { "word": "confidence", "translation": "信心，自信" },
        { "word": "curious", "translation": "好奇的，求知欲强的" },
        { "word": "design", "translation": "设计，计划" },
        { "word": "destination", "translation": "目的地，终点" },
        { "word": "exchange", "translation": "交换，交流" },
        { "word": "experiment", "translation": "实验，试验" },
        { "word": "explore", "translation": "探索，探究" },
        { "word": "female", "translation": "女性的，雌性的" },
        { "word": "formal", "translation": "正式的，正规的" },
        { "word": "forward", "translation": "向前，前进" },
        { "word": "frightened", "translation": "害怕的，受惊的" },
        { "word": "goal", "translation": "目标，目的" },
        { "word": "improve", "translation": "改善，提高" },
        { "word": "impression", "translation": "印象，感想" },
        { "word": "lecture", "translation": "讲座，演讲" },
        { "word": "male", "translation": "男性的，雄性的" },
        { "word": "nationality", "translation": "国籍，民族" },
        { "word": "organize", "translation": "组织，安排" },
        { "word": "outgoing", "translation": "外向的，爱交际的" },
        { "word": "partner", "translation": "伙伴，合作者" },
        { "word": "personality", "translation": "个性，人格" },
        { "word": "register", "translation": "登记，注册" },
        { "word": "registration", "translation": "登记，注册" },
        { "word": "revise", "translation": "复习，修订" },
        { "word": "senior", "translation": "高级的，年长的" },
        { "word": "strategy", "translation": "策略，战略" }
      ],
      "词组": [
        { "phrase": "at last", "translation": "终于，最后" },
        { "phrase": "concentrate on", "translation": "集中注意力于" },
        { "phrase": "exchange student", "translation": "交换生" },
        { "phrase": "first impression", "translation": "第一印象" },
        { "phrase": "leave alone", "translation": "不打扰，不干涉" },
        { "phrase": "look forward to", "translation": "期待，盼望" },
        { "phrase": "make friends", "translation": "交朋友" },
        { "phrase": "take notes", "translation": "做笔记" },
        { "phrase": "what if", "translation": "如果...会怎样" }
      ]
    },
    "Unit 1 Teenage Life": {
      "词汇": [
        { "word": "actually", "translation": "实际上，事实上" },
        { "word": "addicted", "translation": "上瘾的，入迷的" },
        { "word": "adventure", "translation": "冒险，奇遇" },
        { "word": "adult", "translation": "成年人，成年的" },
        { "word": "advance", "translation": "前进，进步" },
        { "word": "behavior", "translation": "行为，举止" },
        { "word": "challenge", "translation": "挑战，质疑" },
        { "word": "champion", "translation": "冠军，优胜者" },
        { "word": "clean", "translation": "清洁的，打扫" },
        { "word": "club", "translation": "俱乐部，社团" },
        { "word": "confuse", "translation": "使困惑，混淆" },
        { "word": "content", "translation": "内容，满足的" },
        { "word": "debate", "translation": "辩论，争论" },
        { "word": "editor", "translation": "编辑，编者" },
        { "word": "expert", "translation": "专家，熟练的" },
        { "word": "extra", "translation": "额外的，另外的" },
        { "word": "fluent", "translation": "流利的，流畅的" },
        { "word": "focus", "translation": "集中，焦点" },
        { "word": "freshman", "translation": "大一新生，新手" },
        { "word": "generation", "translation": "一代，产生" },
        { "word": "graduate", "translation": "毕业，毕业生" },
        { "word": "literature", "translation": "文学，文献" },
        { "word": "movement", "translation": "运动，移动" },
        { "word": "obviously", "translation": "明显地，显然" },
        { "word": "prefer", "translation": "更喜欢，偏爱" },
        { "word": "quit", "translation": "退出，放弃" },
        { "word": "recommend", "translation": "推荐，建议" },
        { "word": "responsible", "translation": "负责的，可靠的" },
        { "word": "schedule", "translation": "日程表，安排" },
        { "word": "solution", "translation": "解决方案，答案" },
        { "word": "suitable", "translation": "合适的，适当的" },
        { "word": "survival", "translation": "生存，幸存" },
        { "word": "teenage", "translation": "青少年的" },
        { "word": "teenager", "translation": "青少年" },
        { "word": "title", "translation": "标题，头衔" },
        { "word": "topic", "translation": "话题，主题" },
        { "word": "volunteer", "translation": "志愿者，自愿" },
        { "word": "youth", "translation": "青年，青春" }
      ],
      "词组": [
        { "phrase": "be attracted to", "translation": "被...吸引" },
        { "phrase": "be responsible for", "translation": "对...负责" },
        { "phrase": "clean up", "translation": "打扫干净，清理" },
        { "phrase": "focus on", "translation": "集中于，专注于" },
        { "phrase": "prefer to", "translation": "更喜欢，宁愿" },
        { "phrase": "sign up for", "translation": "报名参加" },
        { "phrase": "suitable for", "translation": "适合于" }
      ]
    },
    "Unit 2 Travelling Around": {
      "词汇": [
        { "word": "accommodation", "translation": "住宿，住处" },
        { "word": "admire", "translation": "钦佩，欣赏" },
        { "word": "amazing", "translation": "令人惊奇的" },
        { "word": "apply", "translation": "申请，应用" },
        { "word": "architecture", "translation": "建筑学，建筑风格" },
        { "word": "arrangement", "translation": "安排，布置" },
        { "word": "castle", "translation": "城堡" },
        { "word": "check", "translation": "检查，核对" },
        { "word": "civilization", "translation": "文明，文化" },
        { "word": "comment", "translation": "评论，意见" },
        { "word": "contact", "translation": "联系，接触" },
        { "word": "credit", "translation": "信用，学分" },
        { "word": "destination", "translation": "目的地，终点" },
        { "word": "economy", "translation": "经济，节约" },
        { "word": "empire", "translation": "帝国" },
        { "word": "extremely", "translation": "极其，非常" },
        { "word": "flat", "translation": "平坦的，公寓" },
        { "word": "flight", "translation": "航班，飞行" },
        { "word": "hike", "translation": "徒步旅行" },
        { "word": "narrow", "translation": "狭窄的" },
        { "word": "official", "translation": "官方的，正式的" },
        { "word": "pack", "translation": "打包，包裹" },
        { "word": "package", "translation": "包裹，套餐" },
        { "word": "path", "translation": "小路，路径" },
        { "word": "powerful", "translation": "强大的，有力的" },
        { "word": "recognize", "translation": "认出，承认" },
        { "word": "rent", "translation": "租用，租金" },
        { "word": "request", "translation": "请求，要求" },
        { "word": "reserve", "translation": "预订，保留" },
        { "word": "site", "translation": "地点，场所" },
        { "word": "soldier", "translation": "士兵，军人" },
        { "word": "source", "translation": "来源，源头" },
        { "word": "statue", "translation": "雕像，塑像" },
        { "word": "tomb", "translation": "坟墓，陵墓" },
        { "word": "transport", "translation": "运输，交通工具" },
        { "word": "unique", "translation": "独特的，唯一的" },
        { "word": "view", "translation": "景色，观点" },
        { "word": "visa", "translation": "签证" }
      ],
      "词组": [
        { "phrase": "apply for", "translation": "申请" },
        { "phrase": "check in", "translation": "登记入住" },
        { "phrase": "check out", "translation": "结账离开" },
        { "phrase": "credit card", "translation": "信用卡" },
        { "phrase": "look forward to", "translation": "期待，盼望" },
        { "phrase": "make up", "translation": "构成，编造" },
        { "phrase": "other than", "translation": "除了" },
        { "phrase": "take control of", "translation": "控制，掌管" }
      ]
    },
    "Unit 3 Sports and Fitness": {
      "词汇": [
        { "word": "athlete", "translation": "运动员" },
        { "word": "audience", "translation": "观众，听众" },
        { "word": "boxing", "translation": "拳击" },
        { "word": "captain", "translation": "队长，船长" },
        { "word": "champion", "translation": "冠军" },
        { "word": "championship", "translation": "锦标赛，冠军地位" },
        { "word": "cheat", "translation": "作弊，欺骗" },
        { "word": "compete", "translation": "竞争，比赛" },
        { "word": "determination", "translation": "决心，决定" },
        { "word": "diet", "translation": "饮食，节食" },
        { "word": "error", "translation": "错误，差错" },
        { "word": "event", "translation": "事件，比赛项目" },
        { "word": "failure", "translation": "失败，失败者" },
        { "word": "fitness", "translation": "健康，适合" },
        { "word": "glory", "translation": "荣誉，光荣" },
        { "word": "gymnastics", "translation": "体操" },
        { "word": "honor", "translation": "荣誉，尊敬" },
        { "word": "host", "translation": "主人，主办" },
        { "word": "injure", "translation": "使受伤" },
        { "word": "injury", "translation": "伤害，损伤" },
        { "word": "legend", "translation": "传说，传奇人物" },
        { "word": "master", "translation": "掌握，大师" },
        { "word": "medal", "translation": "奖章，勋章" },
        { "word": "million", "translation": "百万" },
        { "word": "positive", "translation": "积极的，正面的" },
        { "word": "pretend", "translation": "假装，伪装" },
        { "word": "push-up", "translation": "俯卧撑" },
        { "word": "ski", "translation": "滑雪" },
        { "word": "slim", "translation": "苗条的，纤细的" },
        { "word": "soccer", "translation": "足球" },
        { "word": "stadium", "translation": "体育场" },
        { "word": "strength", "translation": "力量，优点" },
        { "word": "stress", "translation": "压力，强调" },
        { "word": "sweat", "translation": "汗水，出汗" },
        { "word": "track", "translation": "跑道，轨道" }
      ],
      "词组": [
        { "phrase": "come along", "translation": "跟着来，进展" },
        { "phrase": "compare with", "translation": "与...比较" },
        { "phrase": "compete with", "translation": "与...竞争" },
        { "phrase": "even if", "translation": "即使，尽管" },
        { "phrase": "fall apart", "translation": "崩溃，破碎" },
        { "phrase": "give up", "translation": "放弃" },
        { "phrase": "lose heart", "translation": "丧失信心" },
        { "phrase": "make a difference", "translation": "有影响，起作用" },
        { "phrase": "make sense", "translation": "有意义，讲得通" },
        { "phrase": "make it", "translation": "成功，达到" },
        { "phrase": "work out", "translation": "锻炼，解决" }
      ]
    },
    "Unit 4 Natural Disasters": {
      "词汇": [
        { "word": "affect", "translation": "影响，感动" },
        { "word": "breathe", "translation": "呼吸" },
        { "word": "brick", "translation": "砖，砖块" },
        { "word": "bury", "translation": "埋葬，掩埋" },
        { "word": "crash", "translation": "碰撞，崩溃" },
        { "word": "damage", "translation": "损害，损失" },
        { "word": "death", "translation": "死亡" },
        { "word": "deliver", "translation": "递送，发表" },
        { "word": "destroy", "translation": "破坏，毁灭" },
        { "word": "disaster", "translation": "灾难，灾害" },
        { "word": "electricity", "translation": "电，电力" },
        { "word": "emergency", "translation": "紧急情况" },
        { "word": "flood", "translation": "洪水，水灾" },
        { "word": "kit", "translation": "成套工具，装备" },
        { "word": "length", "translation": "长度" },
        { "word": "magnitude", "translation": "震级，重要性" },
        { "word": "metal", "translation": "金属" },
        { "word": "percent", "translation": "百分比" },
        { "word": "pipe", "translation": "管道，烟斗" },
        { "word": "power", "translation": "力量，权力" },
        { "word": "rescue", "translation": "营救，救援" },
        { "word": "revive", "translation": "复活，恢复" },
        { "word": "ruin", "translation": "毁坏，废墟" },
        { "word": "shelter", "translation": "避难所，庇护" },
        { "word": "shock", "translation": "震惊，休克" },
        { "word": "strike", "translation": "袭击，罢工" },
        { "word": "suffer", "translation": "遭受，忍受" },
        { "word": "supply", "translation": "供应，补给" },
        { "word": "survive", "translation": "幸存，存活" },
        { "word": "tap", "translation": "轻敲，水龙头" },
        { "word": "trap", "translation": "困住，陷阱" },
        { "word": "unify", "translation": "统一，团结" },
        { "word": "wave", "translation": "波浪，挥手" },
        { "word": "whistle", "translation": "口哨，吹口哨" },
        { "word": "wisdom", "translation": "智慧，才智" }
      ],
      "词组": [
        { "phrase": "as if", "translation": "好像，仿佛" },
        { "phrase": "as usual", "translation": "像往常一样" },
        { "phrase": "blow away", "translation": "吹走" },
        { "phrase": "come to an end", "translation": "结束" },
        { "phrase": "dig out", "translation": "挖出，发现" },
        { "phrase": "first aid kit", "translation": "急救包" },
        { "phrase": "in ruins", "translation": "成为废墟" },
        { "phrase": "in shock", "translation": "震惊，休克状态" },
        { "phrase": "on hand", "translation": "在手边，现有" },
        { "phrase": "suffer from", "translation": "遭受，患病" }
      ]
    },
    "Unit 5 Languages Around the World": {
      "词汇": [
        { "word": "appreciate", "translation": "欣赏，感激" },
        { "word": "attitude", "translation": "态度，看法" },
        { "word": "base", "translation": "基础，基地" },
        { "word": "billion", "translation": "十亿" },
        { "word": "bone", "translation": "骨头" },
        { "word": "calligraphy", "translation": "书法" },
        { "word": "carve", "translation": "雕刻" },
        { "word": "character", "translation": "汉字，性格" },
        { "word": "classic", "translation": "经典的，古典的" },
        { "word": "civilisation", "translation": "文明" },
        { "word": "demand", "translation": "要求，需求" },
        { "word": "description", "translation": "描述，说明" },
        { "word": "despite", "translation": "尽管，不管" },
        { "word": "dialect", "translation": "方言，地方话" },
        { "word": "dynasty", "translation": "朝代，王朝" },
        { "word": "equal", "translation": "平等的，相等的" },
        { "word": "factor", "translation": "因素，要素" },
        { "word": "gap", "translation": "差距，缺口" },
        { "word": "global", "translation": "全球的，全面的" },
        { "word": "major", "translation": "主要的，专业" },
        { "word": "means", "translation": "方式，手段" },
        { "word": "native", "translation": "本土的，母语的" },
        { "word": "refer", "translation": "提到，参考" },
        { "word": "regard", "translation": "认为，看待" },
        { "word": "relate", "translation": "联系，叙述" },
        { "word": "semester", "translation": "学期" },
        { "word": "shell", "translation": "贝壳，外壳" },
        { "word": "specific", "translation": "具体的，特定的" },
        { "word": "struggle", "translation": "斗争，奋斗" },
        { "word": "symbol", "translation": "符号，象征" },
        { "word": "system", "translation": "系统，体系" },
        { "word": "tongue", "translation": "舌头，语言" },
        { "word": "ups", "translation": "起伏" },
        { "word": "variety", "translation": "多样性，种类" },
        { "word": "vocabulary", "translation": "词汇，词汇量" }
      ],
      "词组": [
        { "phrase": "date back to", "translation": "追溯到" },
        { "phrase": "no matter", "translation": "无论，不管" },
        { "phrase": "point of view", "translation": "观点，看法" },
        { "phrase": "refer to", "translation": "提到，参考" },
        { "phrase": "relate to", "translation": "与...有关" },
        { "phrase": "ups and downs", "translation": "起起伏伏，兴衰" }
      ]
    }
  }
};

if(typeof window !== "undefined" && typeof window.registerTextbookBook === "function"){
  window.registerTextbookBook("requiredBook1", requiredBook1);
}
