const requiredBook3 = {
  "必修第三册": {
    "Unit 1 Festivals and Celebrations": {
      "词汇": [
        { "word": "agriculture", "translation": "农业" },
        { "word": "atmosphere", "translation": "气氛，大气" },
        { "word": "belief", "translation": "信仰，信念" },
        { "word": "branch", "translation": "树枝，分支" },
        { "word": "ceremony", "translation": "仪式，典礼" },
        { "word": "charm", "translation": "魅力，吸引力" },
        { "word": "commercial", "translation": "商业的" },
        { "word": "congratulation", "translation": "祝贺" },
        { "word": "costume", "translation": "服装，戏装" },
        { "word": "crop", "translation": "庄稼，作物" },
        { "word": "decorate", "translation": "装饰，装修" },
        { "word": "evil", "translation": "邪恶的，罪恶" },
        { "word": "faith", "translation": "信仰，信任" },
        { "word": "fancy", "translation": "花哨的，想象" },
        { "word": "feature", "translation": "特征，特色" },
        { "word": "figure", "translation": "人物，数字" },
        { "word": "firecracker", "translation": "鞭炮" },
        { "word": "frank", "translation": "坦率的，直率的" },
        { "word": "gather", "translation": "聚集，收集" },
        { "word": "grace", "translation": "优雅，恩典" },
        { "word": "grateful", "translation": "感激的，感谢的" },
        { "word": "harvest", "translation": "收获，收割" },
        { "word": "horror", "translation": "恐怖，恐惧" },
        { "word": "joyful", "translation": "欢乐的，高兴的" },
        { "word": "lantern", "translation": "灯笼" },
        { "word": "lunar", "translation": "月亮的，阴历的" },
        { "word": "march", "translation": "行进，三月" },
        { "word": "medium", "translation": "媒介，中等的" },
        { "word": "merry", "translation": "愉快的，欢乐的" },
        { "word": "moment", "translation": "片刻，时刻" },
        { "word": "occasion", "translation": "场合，时机" },
        { "word": "origin", "translation": "起源，由来" },
        { "word": "pumpkin", "translation": "南瓜" },
        { "word": "range", "translation": "范围，山脉" },
        { "word": "reflect", "translation": "反映，反思" },
        { "word": "religion", "translation": "宗教" },
        { "word": "represent", "translation": "代表，象征" },
        { "word": "respect", "translation": "尊重，尊敬" },
        { "word": "riddle", "translation": "谜语" },
        { "word": "roast", "translation": "烤，烘烤" },
        { "word": "significant", "translation": "重要的，有意义的" },
        { "word": "typical", "translation": "典型的，有代表性的" },
        { "word": "wedding", "translation": "婚礼" },
        { "word": "wrestle", "translation": "摔跤，斗争" }
      ],
      "词组": [
        { "phrase": "after all", "translation": "毕竟，终究" },
        { "phrase": "dress up", "translation": "穿上盛装，打扮" },
        { "phrase": "fade away", "translation": "逐渐消失" },
        { "phrase": "in spite of", "translation": "尽管，不顾" },
        { "phrase": "play a role in", "translation": "在...中起作用" },
        { "phrase": "range from...to", "translation": "从...到...不等" },
        { "phrase": "take advantage of", "translation": "利用" }
      ]
    },
    "Unit 2 Morals and Virtues": {
      "词汇": [
        { "word": "accident", "translation": "事故，意外" },
        { "word": "assist", "translation": "帮助，协助" },
        { "word": "carry", "translation": "携带，运送" },
        { "word": "chain", "translation": "链条，连锁" },
        { "word": "complain", "translation": "抱怨，投诉" },
        { "word": "court", "translation": "法院，球场" },
        { "word": "decade", "translation": "十年" },
        { "word": "despair", "translation": "绝望" },
        { "word": "elect", "translation": "选举，选择" },
        { "word": "elsewhere", "translation": "在别处" },
        { "word": "entrust", "translation": "委托，信任" },
        { "word": "faint", "translation": "晕倒，微弱的" },
        { "word": "flexible", "translation": "灵活的，柔韧的" },
        { "word": "harm", "translation": "伤害，损害" },
        { "word": "hire", "translation": "雇用，租用" },
        { "word": "illustrate", "translation": "说明，阐明" },
        { "word": "insurance", "translation": "保险" },
        { "word": "kindergarten", "translation": "幼儿园" },
        { "word": "lap", "translation": "大腿，一圈" },
        { "word": "majority", "translation": "大多数" },
        { "word": "marriage", "translation": "婚姻" },
        { "word": "memory", "translation": "记忆，记忆力" },
        { "word": "midnight", "translation": "午夜" },
        { "word": "moral", "translation": "道德的，品行" },
        { "word": "operation", "translation": "手术，操作" },
        { "word": "passive", "translation": "被动的，消极的" },
        { "word": "physician", "translation": "医生，内科医生" },
        { "word": "precious", "translation": "珍贵的，宝贵的" },
        { "word": "pregnant", "translation": "怀孕的" },
        { "word": "principle", "translation": "原则，原理" },
        { "word": "publish", "translation": "出版，发表" },
        { "word": "reject", "translation": "拒绝，排斥" },
        { "word": "replace", "translation": "取代，替换" },
        { "word": "respond", "translation": "回应，响应" },
        { "word": "retire", "translation": "退休，退役" },
        { "word": "scare", "translation": "恐吓，惊吓" },
        { "word": "scholarship", "translation": "奖学金，学术" },
        { "word": "sharp", "translation": "锋利的，敏锐的" },
        { "word": "staff", "translation": "员工，全体职员" },
        { "word": "therefore", "translation": "因此，所以" },
        { "word": "union", "translation": "联盟，工会" },
        { "word": "virtue", "translation": "美德，优点" },
        { "word": "waitress", "translation": "女服务员" },
        { "word": "whisper", "translation": "低语，耳语" }
      ],
      "词组": [
        { "phrase": "carry through", "translation": "坚持到底，完成" },
        { "phrase": "first aid", "translation": "急救" },
        { "phrase": "in despair", "translation": "绝望地" },
        { "phrase": "in memory of", "translation": "为纪念" },
        { "phrase": "in tears", "translation": "流着泪，含泪" },
        { "phrase": "pass away", "translation": "去世" },
        { "phrase": "tend to", "translation": "倾向于，照料" },
        { "phrase": "trip over", "translation": "绊倒" }
      ]
    },
    "Unit 3 Diverse Cultures": {
      "词汇": [
        { "word": "admit", "translation": "承认，准许进入" },
        { "word": "afterwards", "translation": "后来，然后" },
        { "word": "bar", "translation": "酒吧，条" },
        { "word": "cheese", "translation": "奶酪" },
        { "word": "china", "translation": "瓷器" },
        { "word": "chip", "translation": "薯条，芯片" },
        { "word": "claim", "translation": "声称，要求" },
        { "word": "climate", "translation": "气候" },
        { "word": "collection", "translation": "收藏，收集" },
        { "word": "construction", "translation": "建设，建筑" },
        { "word": "contain", "translation": "包含，容纳" },
        { "word": "definitely", "translation": "肯定地，明确地" },
        { "word": "diagram", "translation": "图表，图解" },
        { "word": "district", "translation": "地区，区域" },
        { "word": "downtown", "translation": "市中心，商业区" },
        { "word": "earn", "translation": "赚得，挣得" },
        { "word": "escape", "translation": "逃跑，逃避" },
        { "word": "ethnic", "translation": "民族的，种族的" },
        { "word": "financial", "translation": "财政的，金融的" },
        { "word": "fold", "translation": "折叠，褶皱" },
        { "word": "fortune", "translation": "财富，运气" },
        { "word": "graffiti", "translation": "涂鸦" },
        { "word": "heading", "translation": "标题，前进" },
        { "word": "immigrant", "translation": "移民" },
        { "word": "item", "translation": "项目，物品" },
        { "word": "jazz", "translation": "爵士乐" },
        { "word": "journal", "translation": "日记，期刊" },
        { "word": "material", "translation": "材料，物质的" },
        { "word": "mild", "translation": "温和的，温暖的" },
        { "word": "minority", "translation": "少数，少数民族" },
        { "word": "mission", "translation": "使命，任务" },
        { "word": "neat", "translation": "整洁的，整齐的" },
        { "word": "occur", "translation": "发生，出现" },
        { "word": "percentage", "translation": "百分比" },
        { "word": "poisonous", "translation": "有毒的" },
        { "word": "select", "translation": "选择，挑选" },
        { "word": "series", "translation": "系列，连续" },
        { "word": "settle", "translation": "定居，解决" },
        { "word": "spicy", "translation": "辛辣的" },
        { "word": "suit", "translation": "适合，套装" },
        { "word": "super", "translation": "超级的，极好的" }
      ],
      "词组": [
        { "phrase": "(at) first hand", "translation": "第一手，亲自" },
        { "phrase": "a series of", "translation": "一系列" },
        { "phrase": "apart from", "translation": "除了...之外" },
        { "phrase": "bring about", "translation": "引起，导致" },
        { "phrase": "earn a living", "translation": "谋生" },
        { "phrase": "head to", "translation": "前往" },
        { "phrase": "seek one's fortune", "translation": "寻找财富，碰运气" },
        { "phrase": "to name but a few", "translation": "仅举几例" }
      ]
    },
    "Unit 4 Space Exploration": {
      "词汇": [
        { "word": "agency", "translation": "机构，代理" },
        { "word": "analyse", "translation": "分析" },
        { "word": "argue", "translation": "争论，论证" },
        { "word": "astronaut", "translation": "宇航员" },
        { "word": "attach", "translation": "附加，依恋" },
        { "word": "beyond", "translation": "超出，在...之外" },
        { "word": "closing", "translation": "结束，结尾" },
        { "word": "current", "translation": "当前的，水流" },
        { "word": "data", "translation": "数据，资料" },
        { "word": "desire", "translation": "渴望，欲望" },
        { "word": "determine", "translation": "决定，决心" },
        { "word": "disappointed", "translation": "失望的" },
        { "word": "dock", "translation": "码头，对接" },
        { "word": "fatal", "translation": "致命的，灾难性的" },
        { "word": "frontier", "translation": "边界，前沿" },
        { "word": "giant", "translation": "巨大的，巨人" },
        { "word": "globe", "translation": "地球，球体" },
        { "word": "gravity", "translation": "重力，严重性" },
        { "word": "intelligent", "translation": "聪明的，智能的" },
        { "word": "keen", "translation": "热衷的，敏锐的" },
        { "word": "lack", "translation": "缺乏，不足" },
        { "word": "launch", "translation": "发射，发起" },
        { "word": "leap", "translation": "跳跃，飞跃" },
        { "word": "limited", "translation": "有限的" },
        { "word": "mankind", "translation": "人类" },
        { "word": "mental", "translation": "精神的，脑力的" },
        { "word": "mission", "translation": "使命，任务" },
        { "word": "muscle", "translation": "肌肉" },
        { "word": "mystery", "translation": "神秘，谜" },
        { "word": "ongoing", "translation": "持续的，进行中的" },
        { "word": "orbit", "translation": "轨道，环绕" },
        { "word": "otherwise", "translation": "否则，另外" },
        { "word": "oxygen", "translation": "氧气" },
        { "word": "pattern", "translation": "模式，图案" },
        { "word": "pilot", "translation": "飞行员，引导" },
        { "word": "procedure", "translation": "程序，手续" },
        { "word": "recycle", "translation": "回收，循环" },
        { "word": "regular", "translation": "规律的，定期的" },
        { "word": "resource", "translation": "资源" },
        { "word": "rocket", "translation": "火箭" },
        { "word": "satellite", "translation": "卫星" },
        { "word": "shallow", "translation": "浅的，肤浅的" },
        { "word": "signal", "translation": "信号，标志" },
        { "word": "spacecraft", "translation": "宇宙飞船" },
        { "word": "sufficient", "translation": "足够的，充分的" },
        { "word": "universe", "translation": "宇宙" },
        { "word": "vehicle", "translation": "车辆，载具" }
      ],
      "词组": [
        { "phrase": "as a result", "translation": "结果，因此" },
        { "phrase": "be determined to", "translation": "决心做" },
        { "phrase": "carry on", "translation": "继续，坚持" },
        { "phrase": "figure out", "translation": "弄清楚，算出" },
        { "phrase": "in closing", "translation": "最后" },
        { "phrase": "in the hope of", "translation": "怀着...的希望" },
        { "phrase": "lead to", "translation": "导致，通向" },
        { "phrase": "on board", "translation": "在船上，在飞机上" },
        { "phrase": "provide for", "translation": "提供，供养" },
        { "phrase": "run out", "translation": "用完，耗尽" }
      ]
    },
    "Unit 5 The Value of Money": {
      "词汇": [
        { "word": "apologise", "translation": "道歉" },
        { "word": "basis", "translation": "基础，根据" },
        { "word": "beneath", "translation": "在...下面" },
        { "word": "bet", "translation": "打赌，赌注" },
        { "word": "broad", "translation": "宽阔的，广泛的" },
        { "word": "clerk", "translation": "职员，店员" },
        { "word": "consulate", "translation": "领事馆" },
        { "word": "dare", "translation": "敢，敢于" },
        { "word": "dinosaur", "translation": "恐龙" },
        { "word": "downstairs", "translation": "楼下" },
        { "word": "duty", "translation": "责任，职责" },
        { "word": "element", "translation": "元素，要素" },
        { "word": "embassy", "translation": "大使馆" },
        { "word": "eventually", "translation": "最终，终于" },
        { "word": "external", "translation": "外部的，外面的" },
        { "word": "frown", "translation": "皱眉" },
        { "word": "hesitate", "translation": "犹豫，踌躇" },
        { "word": "honest", "translation": "诚实的，正直的" },
        { "word": "hug", "translation": "拥抱" },
        { "word": "ignore", "translation": "忽视，不理睬" },
        { "word": "indicate", "translation": "表明，指出" },
        { "word": "indeed", "translation": "确实，的确" },
        { "word": "intention", "translation": "意图，打算" },
        { "word": "judge", "translation": "判断，法官" },
        { "word": "loan", "translation": "贷款，借贷" },
        { "word": "maintain", "translation": "维持，保持" },
        { "word": "manner", "translation": "方式，态度" },
        { "word": "matter", "translation": "事情，重要" },
        { "word": "nowhere", "translation": "无处，哪里都不" },
        { "word": "obligation", "translation": "义务，责任" },
        { "word": "odd", "translation": "奇怪的，奇数的" },
        { "word": "option", "translation": "选择，选项" },
        { "word": "patience", "translation": "耐心" },
        { "word": "permit", "translation": "允许，许可证" },
        { "word": "plastic", "translation": "塑料，塑料的" },
        { "word": "plot", "translation": "情节，阴谋" },
        { "word": "postpone", "translation": "推迟，延期" },
        { "word": "pursue", "translation": "追求，追赶" },
        { "word": "sail", "translation": "航行，帆" },
        { "word": "scene", "translation": "场景，现场" },
        { "word": "servant", "translation": "仆人，服务员" },
        { "word": "sort", "translation": "种类，分类" },
        { "word": "spot", "translation": "地点，斑点" },
        { "word": "tailor", "translation": "裁缝" },
        { "word": "upper", "translation": "上面的，上层的" },
        { "word": "willing", "translation": "愿意的，乐意的" }
      ],
      "词组": [
        { "phrase": "as a matter of fact", "translation": "事实上" },
        { "phrase": "be about to", "translation": "即将，正要" },
        { "phrase": "be willing to", "translation": "愿意做" },
        { "phrase": "by accident", "translation": "偶然，意外地" },
        { "phrase": "in case", "translation": "以防万一" },
        { "phrase": "in return", "translation": "作为回报" },
        { "phrase": "make a bet", "translation": "打赌" },
        { "phrase": "on duty", "translation": "值班，当班" },
        { "phrase": "ought to", "translation": "应该" },
        { "phrase": "to be honest", "translation": "说实话" },
        { "phrase": "to tell the truth", "translation": "说实话" }
      ]
    }
  }
};

if(typeof window !== "undefined" && typeof window.registerTextbookBook === "function"){
  window.registerTextbookBook("requiredBook3", requiredBook3);
}
