const electiveBook2 = {
  "选择性必修第二册": {
    "Unit 1 Science and Scientists": {
      "词汇": [
        { "word": "abstract", "translation": "抽象的，摘要" },
        { "word": "astronomy", "translation": "天文学" },
        { "word": "blame", "translation": "责备，归咎于" },
        { "word": "brilliant", "translation": "杰出的，辉煌的" },
        { "word": "cast", "translation": "投射，铸造" },
        { "word": "cell", "translation": "细胞，小房间" },
        { "word": "concept", "translation": "概念，观念" },
        { "word": "concrete", "translation": "具体的，混凝土" },
        { "word": "contradictory", "translation": "矛盾的，对立的" },
        { "word": "defend", "translation": "保卫，辩护" },
        { "word": "framework", "translation": "框架，结构" },
        { "word": "frustrated", "translation": "沮丧的，挫败的" },
        { "word": "handle", "translation": "处理，把手" },
        { "word": "household", "translation": "家庭，家庭的" },
        { "word": "infection", "translation": "感染，传染" },
        { "word": "initial", "translation": "最初的，首字母" },
        { "word": "intervention", "translation": "干预，介入" },
        { "word": "link", "translation": "联系，连接" },
        { "word": "microscope", "translation": "显微镜" },
        { "word": "multiple", "translation": "多个的，多重的" },
        { "word": "outstanding", "translation": "杰出的，未解决的" },
        { "word": "pour", "translation": "倒，倾泻" },
        { "word": "proof", "translation": "证明，证据" },
        { "word": "protein", "translation": "蛋白质" },
        { "word": "pump", "translation": "泵，抽水" },
        { "word": "pure", "translation": "纯净的，纯粹的" },
        { "word": "raw", "translation": "生的，未加工的" },
        { "word": "severe", "translation": "严重的，严厉的" },
        { "word": "solid", "translation": "固体的，坚固的" },
        { "word": "statistic", "translation": "统计数据" },
        { "word": "subscribe", "translation": "订阅，赞同" },
        { "word": "substantial", "translation": "大量的，实质的" },
        { "word": "suspect", "translation": "怀疑，嫌疑犯" },
        { "word": "transform", "translation": "转变，改造" },
        { "word": "virus", "translation": "病毒" }
      ],
      "词组": [
        { "phrase": "above all", "translation": "首先，尤其是" },
        { "phrase": "be to blame", "translation": "应受责备" },
        { "phrase": "come down with", "translation": "患病，染上" },
        { "phrase": "once and for all", "translation": "一劳永逸地" },
        { "phrase": "subscribe to", "translation": "订阅，同意" },
        { "phrase": "thanks to", "translation": "多亏，由于" }
      ]
    },
    "Unit 2 Bridging Cultures": {
      "词汇": [
        { "word": "ambitious", "translation": "有抱负的，雄心勃勃的" },
        { "word": "angle", "translation": "角度，观点" },
        { "word": "applicant", "translation": "申请人" },
        { "word": "behave", "translation": "表现，举止" },
        { "word": "budget", "translation": "预算" },
        { "word": "cite", "translation": "引用，引证" },
        { "word": "competence", "translation": "能力，胜任" },
        { "word": "complex", "translation": "复杂的，综合体" },
        { "word": "cooperate", "translation": "合作，配合" },
        { "word": "depart", "translation": "离开，出发" },
        { "word": "depressed", "translation": "沮丧的，萧条的" },
        { "word": "deny", "translation": "否认，拒绝" },
        { "word": "dramatic", "translation": "戏剧性的，引人注目的" },
        { "word": "engage", "translation": "从事，吸引" },
        { "word": "exposure", "translation": "暴露，曝光" },
        { "word": "firm", "translation": "坚定的，公司" },
        { "word": "gain", "translation": "获得，增加" },
        { "word": "grasp", "translation": "抓住，理解" },
        { "word": "homesick", "translation": "想家的" },
        { "word": "initiative", "translation": "主动性，倡议" },
        { "word": "insight", "translation": "洞察力，见解" },
        { "word": "involve", "translation": "涉及，使参与" },
        { "word": "logical", "translation": "逻辑的，合理的" },
        { "word": "mature", "translation": "成熟的" },
        { "word": "motivate", "translation": "激励，激发" },
        { "word": "optimistic", "translation": "乐观的" },
        { "word": "outcome", "translation": "结果，成果" },
        { "word": "overwhelming", "translation": "压倒性的，势不可挡的" },
        { "word": "perspective", "translation": "观点，视角" },
        { "word": "presentation", "translation": "演示，介绍" },
        { "word": "qualify", "translation": "使合格，限定" },
        { "word": "recall", "translation": "回忆，召回" },
        { "word": "reasonable", "translation": "合理的，公道的" },
        { "word": "setting", "translation": "环境，背景" },
        { "word": "sincerely", "translation": "真诚地" },
        { "word": "strengthen", "translation": "加强，巩固" },
        { "word": "surroundings", "translation": "环境，周围事物" },
        { "word": "tutor", "translation": "导师，辅导" }
      ],
      "词组": [
        { "phrase": "as far as I am concerned", "translation": "就我而言" },
        { "phrase": "as far as I know", "translation": "据我所知" },
        { "phrase": "contribute to", "translation": "有助于，贡献" },
        { "phrase": "cost an arm and a leg", "translation": "非常昂贵" },
        { "phrase": "engage in", "translation": "从事，参与" },
        { "phrase": "feel at home", "translation": "感到自在" },
        { "phrase": "get involved in", "translation": "参与，卷入" },
        { "phrase": "in addition", "translation": "另外，此外" },
        { "phrase": "in summary", "translation": "总之，概括地说" },
        { "phrase": "participate in", "translation": "参加，参与" },
        { "phrase": "side with", "translation": "支持，站在...一边" },
        { "phrase": "speak up", "translation": "大声说，畅所欲言" }
      ]
    },
    "Unit 3 Food and Culture": {
      "词汇": [
        { "word": "association", "translation": "协会，联想" },
        { "word": "bold", "translation": "大胆的，粗体的" },
        { "word": "brand", "translation": "品牌，商标" },
        { "word": "calorie", "translation": "卡路里，热量" },
        { "word": "canteen", "translation": "食堂，餐厅" },
        { "word": "category", "translation": "类别，种类" },
        { "word": "chew", "translation": "咀嚼，深思" },
        { "word": "consist", "translation": "组成，构成" },
        { "word": "consume", "translation": "消费，消耗" },
        { "word": "cuisine", "translation": "烹饪，菜肴" },
        { "word": "delicate", "translation": "精致的，脆弱的" },
        { "word": "dessert", "translation": "甜点" },
        { "word": "elegant", "translation": "优雅的，精美的" },
        { "word": "exceptional", "translation": "异常的，杰出的" },
        { "word": "fibre", "translation": "纤维" },
        { "word": "flavour", "translation": "味道，风味" },
        { "word": "fundamental", "translation": "基本的，根本的" },
        { "word": "garlic", "translation": "大蒜" },
        { "word": "ideal", "translation": "理想的，理想" },
        { "word": "ingredient", "translation": "成分，原料" },
        { "word": "junk", "translation": "垃圾，废物" },
        { "word": "lamb", "translation": "羊羔，羊肉" },
        { "word": "madam", "translation": "女士，夫人" },
        { "word": "minimum", "translation": "最小的，最少的" },
        { "word": "modest", "translation": "谦虚的，适度的" },
        { "word": "olive", "translation": "橄榄" },
        { "word": "pepper", "translation": "胡椒，辣椒" },
        { "word": "portion", "translation": "部分，一份" },
        { "word": "prior", "translation": "先前的，优先的" },
        { "word": "quantity", "translation": "数量，大量" },
        { "word": "recipe", "translation": "食谱，配方" },
        { "word": "regardless", "translation": "不管，不顾" },
        { "word": "stable", "translation": "稳定的，马厩" },
        { "word": "stew", "translation": "炖，炖菜" },
        { "word": "stuff", "translation": "东西，填充" },
        { "word": "temper", "translation": "脾气，性情" },
        { "word": "trick", "translation": "诡计，技巧" },
        { "word": "vegetarian", "translation": "素食者" },
        { "word": "vitamin", "translation": "维生素" }
      ],
      "词组": [
        { "phrase": "consist of", "translation": "由...组成" },
        { "phrase": "prior to", "translation": "在...之前" },
        { "phrase": "regardless of", "translation": "不管，不顾" },
        { "phrase": "relate to", "translation": "与...有关" }
      ]
    },
    "Unit 4 Journey Across a Vast Land": {
      "词汇": [
        { "word": "antique", "translation": "古董，古老的" },
        { "word": "arise", "translation": "出现，起身" },
        { "word": "astonish", "translation": "使惊讶" },
        { "word": "awesome", "translation": "令人敬畏的，极好的" },
        { "word": "border", "translation": "边界，边境" },
        { "word": "bound", "translation": "跳跃，必定的" },
        { "word": "bunch", "translation": "束，串" },
        { "word": "contrary", "translation": "相反的，对立的" },
        { "word": "craft", "translation": "工艺，手艺" },
        { "word": "curtain", "translation": "窗帘，幕布" },
        { "word": "duration", "translation": "持续时间" },
        { "word": "frost", "translation": "霜，霜冻" },
        { "word": "harbour", "translation": "港口，庇护" },
        { "word": "highlight", "translation": "突出，强调" },
        { "word": "idiom", "translation": "习语，成语" },
        { "word": "literally", "translation": "字面上地，确实地" },
        { "word": "massive", "translation": "巨大的，大量的" },
        { "word": "mist", "translation": "薄雾，迷雾" },
        { "word": "mount", "translation": "山，安装" },
        { "word": "owe", "translation": "欠，归功于" },
        { "word": "peak", "translation": "山峰，顶峰" },
        { "word": "photographer", "translation": "摄影师" },
        { "word": "pleasant", "translation": "愉快的，宜人的" },
        { "word": "proceed", "translation": "继续，进行" },
        { "word": "quarry", "translation": "采石场，猎物" },
        { "word": "scenery", "translation": "风景，景色" },
        { "word": "shore", "translation": "海岸，岸边" },
        { "word": "spectacular", "translation": "壮观的，引人注目的" },
        { "word": "steel", "translation": "钢，钢铁" },
        { "word": "thunder", "translation": "雷，轰鸣" },
        { "word": "toast", "translation": "吐司，祝酒" },
        { "word": "typical", "translation": "典型的，有代表性的" }
      ],
      "词组": [
        { "phrase": "a bunch of", "translation": "一束，一群" },
        { "phrase": "all the way", "translation": "一路上，自始至终" },
        { "phrase": "bound for", "translation": "前往，开往" },
        { "phrase": "contrary to", "translation": "与...相反" },
        { "phrase": "owe...to", "translation": "把...归功于" },
        { "phrase": "pull back", "translation": "撤退，拉回" },
        { "phrase": "take sb's breath away", "translation": "令人惊叹" }
      ]
    },
    "Unit 5 First Aid": {
      "词汇": [
        { "word": "acid", "translation": "酸，酸性的" },
        { "word": "ambulance", "translation": "救护车" },
        { "word": "ankle", "translation": "脚踝" },
        { "word": "bath", "translation": "洗澡，浴缸" },
        { "word": "bleed", "translation": "流血，出血" },
        { "word": "blister", "translation": "水泡" },
        { "word": "carpet", "translation": "地毯" },
        { "word": "collapse", "translation": "倒塌，崩溃" },
        { "word": "delay", "translation": "延迟，耽搁" },
        { "word": "desperate", "translation": "绝望的，急切的" },
        { "word": "drown", "translation": "淹死，淹没" },
        { "word": "ease", "translation": "减轻，安逸" },
        { "word": "elderly", "translation": "年长的，老年的" },
        { "word": "electric", "translation": "电的，电动的" },
        { "word": "fabric", "translation": "织物，布料" },
        { "word": "face", "translation": "面对，脸" },
        { "word": "grab", "translation": "抓住，攫取" },
        { "word": "interrupt", "translation": "打断，中断" },
        { "word": "justify", "translation": "证明...正当，辩护" },
        { "word": "layer", "translation": "层，层次" },
        { "word": "leather", "translation": "皮革" },
        { "word": "loose", "translation": "松的，宽松的" },
        { "word": "minor", "translation": "较小的，未成年的" },
        { "word": "nerve", "translation": "神经，勇气" },
        { "word": "organ", "translation": "器官，机构" },
        { "word": "panic", "translation": "恐慌，惊慌" },
        { "word": "paramedic", "translation": "护理人员，医务辅助人员" },
        { "word": "practical", "translation": "实用的，实际的" },
        { "word": "press", "translation": "按压，新闻界" },
        { "word": "radiation", "translation": "辐射，放射" },
        { "word": "ray", "translation": "光线，射线" },
        { "word": "scream", "translation": "尖叫，喊叫" },
        { "word": "sense", "translation": "感觉，意识" },
        { "word": "slip", "translation": "滑倒，滑动" },
        { "word": "sprain", "translation": "扭伤" },
        { "word": "squeeze", "translation": "挤压，压榨" },
        { "word": "swallow", "translation": "吞咽，燕子" },
        { "word": "swollen", "translation": "肿胀的" },
        { "word": "technique", "translation": "技术，技巧" },
        { "word": "throat", "translation": "喉咙，咽喉" },
        { "word": "tight", "translation": "紧的，紧密的" },
        { "word": "underneath", "translation": "在...下面" },
        { "word": "urgent", "translation": "紧急的，急迫的" },
        { "word": "victim", "translation": "受害者，牺牲品" },
        { "word": "ward", "translation": "病房，选区" },
        { "word": "wrap", "translation": "包裹，缠绕" }
      ],
      "词组": [
        { "phrase": "act as", "translation": "充当，起...作用" },
        { "phrase": "come into contact with", "translation": "与...接触" },
        { "phrase": "electric shock", "translation": "触电，电击" },
        { "phrase": "help sb to one's feet", "translation": "扶某人站起来" },
        { "phrase": "sense of touch", "translation": "触觉" },
        { "phrase": "stick to", "translation": "坚持，粘住" }
      ]
    }
  }
};

if(typeof window !== "undefined" && typeof window.registerTextbookBook === "function"){
  window.registerTextbookBook("electiveBook2", electiveBook2);
}
