const electiveBook1 = {
  "选择性必修第一册": {
    "Unit 1 People of Achievement": {
      "词汇": [
        { "word": "academy", "translation": "学院，研究院" },
        { "word": "acknowledge", "translation": "承认，感谢" },
        { "word": "analyse", "translation": "分析，分解" },
        { "word": "apparent", "translation": "显然的，明显的" },
        { "word": "boil", "translation": "煮沸，沸腾" },
        { "word": "botanical", "translation": "植物学的" },
        { "word": "circumstance", "translation": "环境，情况" },
        { "word": "commit", "translation": "承诺，犯罪" },
        { "word": "conclusion", "translation": "结论，结束" },
        { "word": "consequence", "translation": "结果，后果" },
        { "word": "crucial", "translation": "关键的，重要的" },
        { "word": "defeat", "translation": "击败，失败" },
        { "word": "distinct", "translation": "明显的，独特的" },
        { "word": "encounter", "translation": "遭遇，遇到" },
        { "word": "evaluate", "translation": "评估，评价" },
        { "word": "extract", "translation": "提取，摘录" },
        { "word": "flow", "translation": "流动，流畅" },
        { "word": "found", "translation": "创立，建立" },
        { "word": "genius", "translation": "天才，天赋" },
        { "word": "gradually", "translation": "逐渐地，渐渐地" },
        { "word": "infer", "translation": "推断，推论" },
        { "word": "insist", "translation": "坚持，坚决要求" },
        { "word": "institution", "translation": "机构，制度" },
        { "word": "obtain", "translation": "获得，得到" },
        { "word": "objective", "translation": "客观的，目标" },
        { "word": "passion", "translation": "激情，热情" },
        { "word": "patent", "translation": "专利，专利权" },
        { "word": "property", "translation": "财产，性质" },
        { "word": "relativity", "translation": "相对论，相对性" },
        { "word": "remarkable", "translation": "非凡的，显著的" },
        { "word": "scientific", "translation": "科学的" },
        { "word": "substance", "translation": "物质，实质" },
        { "word": "theory", "translation": "理论，学说" },
        { "word": "vital", "translation": "至关重要的，生命的" }
      ],
      "词组": [
        { "phrase": "by chance", "translation": "偶然，碰巧" },
        { "phrase": "come to power", "translation": "上台，掌权" },
        { "phrase": "insist on", "translation": "坚持，坚决要求" },
        { "phrase": "lead to", "translation": "导致，通向" },
        { "phrase": "sum up", "translation": "总结，概括" },
        { "phrase": "take up", "translation": "开始从事，占据" }
      ]
    },
    "Unit 2 Looking into the Future": {
      "词汇": [
        { "word": "abnormal", "translation": "不正常的，反常的" },
        { "word": "absence", "translation": "缺席，缺乏" },
        { "word": "accurate", "translation": "精确的，准确的" },
        { "word": "advocate", "translation": "提倡，拥护" },
        { "word": "artificial", "translation": "人工的，人造的" },
        { "word": "automatic", "translation": "自动的" },
        { "word": "available", "translation": "可获得的，可用的" },
        { "word": "cancer", "translation": "癌症" },
        { "word": "cease", "translation": "停止，终止" },
        { "word": "combine", "translation": "结合，联合" },
        { "word": "command", "translation": "命令，指挥" },
        { "word": "constant", "translation": "不断的，恒定的" },
        { "word": "critical", "translation": "批判的，关键的" },
        { "word": "detect", "translation": "发现，察觉" },
        { "word": "efficient", "translation": "效率高的，有效的" },
        { "word": "electrical", "translation": "电的，电气的" },
        { "word": "emphasis", "translation": "强调，重点" },
        { "word": "essay", "translation": "文章，散文" },
        { "word": "fantasy", "translation": "幻想，想象" },
        { "word": "forecast", "translation": "预报，预测" },
        { "word": "hence", "translation": "因此，从此" },
        { "word": "innovation", "translation": "创新，革新" },
        { "word": "instant", "translation": "立即的，速溶的" },
        { "word": "integrate", "translation": "整合，融入" },
        { "word": "knob", "translation": "旋钮，把手" },
        { "word": "leak", "translation": "泄漏，漏洞" },
        { "word": "luxury", "translation": "奢侈，豪华" },
        { "word": "mode", "translation": "模式，方式" },
        { "word": "monitor", "translation": "监控，班长" },
        { "word": "nevertheless", "translation": "然而，不过" },
        { "word": "obey", "translation": "服从，遵守" },
        { "word": "oppose", "translation": "反对，对抗" },
        { "word": "paragraph", "translation": "段落" },
        { "word": "phrase", "translation": "短语，措辞" },
        { "word": "potential", "translation": "潜在的，潜力" },
        { "word": "predict", "translation": "预测，预言" },
        { "word": "preference", "translation": "偏爱，优先" },
        { "word": "prospect", "translation": "前景，展望" },
        { "word": "remote", "translation": "遥远的，偏僻的" },
        { "word": "resist", "translation": "抵抗，抗拒" },
        { "word": "routine", "translation": "常规，日常" },
        { "word": "secure", "translation": "安全的，获得" },
        { "word": "structure", "translation": "结构，构造" },
        { "word": "switch", "translation": "开关，转换" },
        { "word": "warning", "translation": "警告，预警" },
        { "word": "wire", "translation": "电线，金属丝" }
      ],
      "词组": [
        { "phrase": "all in all", "translation": "总的来说" },
        { "phrase": "early on", "translation": "在早期，早先" },
        { "phrase": "in this sense", "translation": "从这个意义上说" },
        { "phrase": "keep in touch with", "translation": "与...保持联系" },
        { "phrase": "switch off", "translation": "关闭，切断" }
      ]
    },
    "Unit 3 Fascinating Parks": {
      "词汇": [
        { "word": "accompany", "translation": "陪伴，伴随" },
        { "word": "adopt", "translation": "采用，收养" },
        { "word": "appeal", "translation": "吸引，呼吁" },
        { "word": "appetite", "translation": "食欲，欲望" },
        { "word": "ban", "translation": "禁止，禁令" },
        { "word": "boundary", "translation": "边界，界限" },
        { "word": "buffet", "translation": "自助餐" },
        { "word": "column", "translation": "柱子，专栏" },
        { "word": "corridor", "translation": "走廊，通道" },
        { "word": "cottage", "translation": "小屋，村舍" },
        { "word": "county", "translation": "县，郡" },
        { "word": "cycle", "translation": "循环，自行车" },
        { "word": "display", "translation": "展示，陈列" },
        { "word": "edge", "translation": "边缘，优势" },
        { "word": "enormous", "translation": "巨大的，庞大的" },
        { "word": "fashion", "translation": "时尚，方式" },
        { "word": "fountain", "translation": "喷泉" },
        { "word": "journalist", "translation": "记者，新闻工作者" },
        { "word": "label", "translation": "标签，标记" },
        { "word": "lung", "translation": "肺" },
        { "word": "prohibit", "translation": "禁止，阻止" },
        { "word": "rare", "translation": "稀有的，罕见的" },
        { "word": "reindeer", "translation": "驯鹿" },
        { "word": "reward", "translation": "奖励，报酬" },
        { "word": "route", "translation": "路线，路径" },
        { "word": "sour", "translation": "酸的，变坏" },
        { "word": "stretch", "translation": "伸展，延伸" },
        { "word": "superb", "translation": "极好的，华丽的" },
        { "word": "swing", "translation": "摇摆，秋千" },
        { "word": "territory", "translation": "领土，领域" },
        { "word": "theme", "translation": "主题" },
        { "word": "valley", "translation": "山谷，峡谷" },
        { "word": "vast", "translation": "广阔的，巨大的" },
        { "word": "visible", "translation": "可见的，明显的" },
        { "word": "wander", "translation": "漫步，徘徊" }
      ],
      "词组": [
        { "phrase": "appeal to", "translation": "吸引，呼吁" },
        { "phrase": "be blessed with", "translation": "有幸拥有" },
        { "phrase": "feed on", "translation": "以...为食" },
        { "phrase": "live off", "translation": "靠...生活" },
        { "phrase": "on the move", "translation": "在行进中，在活动中" },
        { "phrase": "set out", "translation": "出发，开始" },
        { "phrase": "spread out", "translation": "展开，散开" },
        { "phrase": "upside down", "translation": "颠倒，倒置" }
      ]
    },
    "Unit 4 Body Language": {
      "词汇": [
        { "word": "anger", "translation": "愤怒，生气" },
        { "word": "anxiety", "translation": "焦虑，忧虑" },
        { "word": "approve", "translation": "赞成，批准" },
        { "word": "assess", "translation": "评估，评定" },
        { "word": "barrier", "translation": "障碍，屏障" },
        { "word": "barely", "translation": "仅仅，几乎不" },
        { "word": "bend", "translation": "弯曲，屈服" },
        { "word": "bother", "translation": "打扰，烦恼" },
        { "word": "chest", "translation": "胸部，箱子" },
        { "word": "clarify", "translation": "澄清，阐明" },
        { "word": "comparison", "translation": "比较，对比" },
        { "word": "component", "translation": "组成部分，零件" },
        { "word": "conflict", "translation": "冲突，矛盾" },
        { "word": "contrast", "translation": "对比，对照" },
        { "word": "demonstrate", "translation": "证明，演示" },
        { "word": "differ", "translation": "不同，相异" },
        { "word": "distinguish", "translation": "区分，辨别" },
        { "word": "distract", "translation": "分散注意力" },
        { "word": "educator", "translation": "教育工作者" },
        { "word": "embarrassed", "translation": "尴尬的，窘迫的" },
        { "word": "employ", "translation": "雇用，使用" },
        { "word": "favour", "translation": "偏爱，赞成" },
        { "word": "gesture", "translation": "手势，姿态" },
        { "word": "identical", "translation": "相同的，同一的" },
        { "word": "imply", "translation": "暗示，意味" },
        { "word": "incident", "translation": "事件，事故" },
        { "word": "inquire", "translation": "询问，调查" },
        { "word": "internal", "translation": "内部的，内在的" },
        { "word": "interpret", "translation": "解释，口译" },
        { "word": "intervene", "translation": "干预，介入" },
        { "word": "lower", "translation": "降低，较低的" },
        { "word": "merely", "translation": "仅仅，只不过" },
        { "word": "occupy", "translation": "占据，占领" },
        { "word": "perceive", "translation": "察觉，理解" },
        { "word": "pose", "translation": "摆姿势，造成" },
        { "word": "react", "translation": "反应，回应" },
        { "word": "reliable", "translation": "可靠的，可信赖的" },
        { "word": "reveal", "translation": "揭示，透露" },
        { "word": "slight", "translation": "轻微的，细小的" },
        { "word": "stare", "translation": "凝视，盯着看" },
        { "word": "tendency", "translation": "倾向，趋势" },
        { "word": "tone", "translation": "语调，音调" },
        { "word": "trial", "translation": "试验，审判" },
        { "word": "ultimately", "translation": "最终，根本上" },
        { "word": "vary", "translation": "变化，不同" },
        { "word": "witness", "translation": "目击，证人" }
      ],
      "词组": [
        { "phrase": "approve of", "translation": "赞成，同意" },
        { "phrase": "at work", "translation": "在工作，在起作用" },
        { "phrase": "be ashamed of", "translation": "为...感到羞愧" },
        { "phrase": "break down", "translation": "分解，崩溃" },
        { "phrase": "by comparison", "translation": "相比之下" },
        { "phrase": "by contrast", "translation": "相反，对比之下" },
        { "phrase": "call on", "translation": "拜访，号召" },
        { "phrase": "make assessments", "translation": "进行评估" },
        { "phrase": "make inferences", "translation": "做出推断" },
        { "phrase": "straighten up", "translation": "挺直，整理" }
      ]
    },
    "Unit 5 Working the Land": {
      "词汇": [
        { "word": "alternative", "translation": "替代的，选择" },
        { "word": "aspect", "translation": "方面，外表" },
        { "word": "attain", "translation": "达到，获得" },
        { "word": "bomb", "translation": "炸弹，轰炸" },
        { "word": "boost", "translation": "促进，增强" },
        { "word": "celebrity", "translation": "名人，名声" },
        { "word": "characteristic", "translation": "特征，特色" },
        { "word": "chemical", "translation": "化学的，化学品" },
        { "word": "comprise", "translation": "包括，由...组成" },
        { "word": "consumption", "translation": "消费，消耗" },
        { "word": "conventional", "translation": "传统的，常规的" },
        { "word": "convince", "translation": "说服，使确信" },
        { "word": "crisis", "translation": "危机，危急" },
        { "word": "deep", "translation": "深的，深刻的" },
        { "word": "devote", "translation": "奉献，致力于" },
        { "word": "domestic", "translation": "国内的，家庭的" },
        { "word": "entirely", "translation": "完全地，彻底地" },
        { "word": "essential", "translation": "必要的，本质的" },
        { "word": "estimate", "translation": "估计，估价" },
        { "word": "expand", "translation": "扩大，扩展" },
        { "word": "extension", "translation": "延伸，扩展" },
        { "word": "fertiliser", "translation": "肥料，化肥" },
        { "word": "generation", "translation": "一代，产生" },
        { "word": "grain", "translation": "谷物，颗粒" },
        { "word": "intense", "translation": "强烈的，紧张的" },
        { "word": "leisure", "translation": "休闲，空闲" },
        { "word": "mineral", "translation": "矿物，矿物质" },
        { "word": "nutritional", "translation": "营养的" },
        { "word": "organic", "translation": "有机的，器官的" },
        { "word": "output", "translation": "产量，输出" },
        { "word": "overcome", "translation": "克服，战胜" },
        { "word": "pesticide", "translation": "农药，杀虫剂" },
        { "word": "poverty", "translation": "贫穷，贫困" },
        { "word": "reality", "translation": "现实，真实" },
        { "word": "root", "translation": "根，根源" },
        { "word": "shortage", "translation": "短缺，不足" },
        { "word": "soil", "translation": "土壤，土地" },
        { "word": "strain", "translation": "压力，品种" },
        { "word": "tackle", "translation": "处理，解决" },
        { "word": "urban", "translation": "城市的，都市的" },
        { "word": "vision", "translation": "视力，愿景" },
        { "word": "wheat", "translation": "小麦" },
        { "word": "widespread", "translation": "广泛的，普遍的" },
        { "word": "yield", "translation": "产量，屈服" }
      ],
      "词组": [
        { "phrase": "be comprised of", "translation": "由...组成" },
        { "phrase": "convince sb of sth", "translation": "使某人相信某事" },
        { "phrase": "deep down", "translation": "在内心深处" },
        { "phrase": "devote oneself to", "translation": "致力于，献身于" },
        { "phrase": "in turn", "translation": "依次，反过来" },
        { "phrase": "open up", "translation": "开放，开辟" }
      ]
    }
  }
};

if(typeof window !== "undefined" && typeof window.registerTextbookBook === "function"){
  window.registerTextbookBook("electiveBook1", electiveBook1);
}
