const electiveBook3 = {
  "选择性必修第三册": {
    "Unit 1 Art": {
      "词汇": [
        { "word": "breakthrough", "translation": "突破，重大进展" },
        { "word": "bronze", "translation": "青铜，铜像" },
        { "word": "client", "translation": "客户，委托人" },
        { "word": "convey", "translation": "传达，表达" },
        { "word": "decline", "translation": "下降，衰退" },
        { "word": "emerge", "translation": "出现，浮现" },
        { "word": "entry", "translation": "进入，条目" },
        { "word": "exhibition", "translation": "展览，展示" },
        { "word": "frame", "translation": "框架，画框" },
        { "word": "guarantee", "translation": "保证，担保" },
        { "word": "humanistic", "translation": "人文主义的" },
        { "word": "influence", "translation": "影响，势力" },
        { "word": "investment", "translation": "投资" },
        { "word": "magnificent", "translation": "壮丽的，华丽的" },
        { "word": "memorial", "translation": "纪念碑，纪念的" },
        { "word": "mythology", "translation": "神话，神话学" },
        { "word": "noble", "translation": "高贵的，贵族" },
        { "word": "permanent", "translation": "永久的，持久的" },
        { "word": "photography", "translation": "摄影，摄影术" },
        { "word": "precise", "translation": "精确的，准确的" },
        { "word": "primitive", "translation": "原始的，简单的" },
        { "word": "purchase", "translation": "购买，采购" },
        { "word": "rank", "translation": "等级，排名" },
        { "word": "realistic", "translation": "现实的，逼真的" },
        { "word": "recognition", "translation": "认可，识别" },
        { "word": "reputation", "translation": "名声，声誉" },
        { "word": "sculpture", "translation": "雕塑，雕刻" },
        { "word": "subsequent", "translation": "随后的，后来的" },
        { "word": "symphony", "translation": "交响乐" },
        { "word": "visual", "translation": "视觉的，看得见的" }
      ],
      "词组": [
        { "phrase": "be fond of", "translation": "喜欢，喜爱" },
        { "phrase": "bring...to life", "translation": "使...生动，赋予生命" },
        { "phrase": "in particular", "translation": "尤其，特别" },
        { "phrase": "set apart from", "translation": "使与众不同" }
      ]
    },
    "Unit 2 Healthy Lifestyle": {
      "词汇": [
        { "word": "abuse", "translation": "滥用，虐待" },
        { "word": "alcohol", "translation": "酒精，酒" },
        { "word": "appropriate", "translation": "适当的，恰当的" },
        { "word": "cue", "translation": "提示，暗示" },
        { "word": "discipline", "translation": "纪律，训练" },
        { "word": "dominate", "translation": "支配，占优势" },
        { "word": "enhance", "translation": "提高，增强" },
        { "word": "examine", "translation": "检查，审查" },
        { "word": "facilitate", "translation": "促进，使便利" },
        { "word": "liberation", "translation": "解放，释放" },
        { "word": "negative", "translation": "消极的，否定的" },
        { "word": "pessimistic", "translation": "悲观的" },
        { "word": "physical", "translation": "身体的，物理的" },
        { "word": "psychology", "translation": "心理学" },
        { "word": "refresh", "translation": "使恢复，刷新" },
        { "word": "rely", "translation": "依靠，信赖" },
        { "word": "repeatedly", "translation": "反复地，再三地" },
        { "word": "reward", "translation": "奖励，报酬" },
        { "word": "shave", "translation": "刮胡子，剃" },
        { "word": "skip", "translation": "跳过，略过" },
        { "word": "specialist", "translation": "专家，专科医生" },
        { "word": "stimulate", "translation": "刺激，激励" },
        { "word": "sugary", "translation": "含糖的，甜的" },
        { "word": "tobacco", "translation": "烟草，香烟" }
      ],
      "词组": [
        { "phrase": "decide on", "translation": "决定，选定" },
        { "phrase": "in response to", "translation": "响应，回应" },
        { "phrase": "rely on", "translation": "依靠，依赖" },
        { "phrase": "straight away", "translation": "立即，马上" }
      ]
    },
    "Unit 3 Environmental Protection": {
      "词汇": [
        { "word": "basin", "translation": "盆地，流域" },
        { "word": "broadcast", "translation": "广播，播送" },
        { "word": "carbon", "translation": "碳" },
        { "word": "chaos", "translation": "混乱，混沌" },
        { "word": "comprehensive", "translation": "综合的，全面的" },
        { "word": "conservation", "translation": "保护，保存" },
        { "word": "disposal", "translation": "处理，处置" },
        { "word": "dozen", "translation": "一打，十二个" },
        { "word": "ecology", "translation": "生态学" },
        { "word": "emission", "translation": "排放，散发" },
        { "word": "fine", "translation": "罚款，精细的" },
        { "word": "fossil", "translation": "化石" },
        { "word": "fuel", "translation": "燃料" },
        { "word": "garbage", "translation": "垃圾，废物" },
        { "word": "graph", "translation": "图表，曲线图" },
        { "word": "habitable", "translation": "适合居住的" },
        { "word": "implement", "translation": "实施，执行" },
        { "word": "inspection", "translation": "检查，视察" },
        { "word": "jungle", "translation": "丛林，密林" },
        { "word": "moderate", "translation": "适度的，温和的" },
        { "word": "nuclear", "translation": "核的，原子能的" },
        { "word": "originate", "translation": "起源，发起" },
        { "word": "penalty", "translation": "处罚，罚款" },
        { "word": "policy", "translation": "政策，方针" },
        { "word": "reform", "translation": "改革，改造" },
        { "word": "regulation", "translation": "规则，管理" },
        { "word": "release", "translation": "释放，发布" },
        { "word": "restore", "translation": "恢复，修复" },
        { "word": "restrict", "translation": "限制，约束" },
        { "word": "seize", "translation": "抓住，夺取" },
        { "word": "submit", "translation": "提交，服从" },
        { "word": "sustainable", "translation": "可持续的" },
        { "word": "tolerate", "translation": "容忍，忍受" },
        { "word": "tropical", "translation": "热带的" },
        { "word": "volume", "translation": "体积，音量" },
        { "word": "waterway", "translation": "水路，航道" }
      ],
      "词组": [
        { "phrase": "along with", "translation": "与...一起" },
        { "phrase": "be trapped in", "translation": "被困在" },
        { "phrase": "bring about", "translation": "引起，导致" },
        { "phrase": "carry out", "translation": "执行，实施" },
        { "phrase": "contribute to", "translation": "有助于，贡献" },
        { "phrase": "dozens of", "translation": "几十个，许多" },
        { "phrase": "have an impact on", "translation": "对...有影响" },
        { "phrase": "in effect", "translation": "实际上，生效" },
        { "phrase": "on behalf of", "translation": "代表" },
        { "phrase": "result in", "translation": "导致，造成" }
      ]
    },
    "Unit 4 Adversity and Courage": {
      "词汇": [
        { "word": "abandon", "translation": "放弃，遗弃" },
        { "word": "aboard", "translation": "在船上，在飞机上" },
        { "word": "adversity", "translation": "逆境，不幸" },
        { "word": "belongings", "translation": "所有物，财产" },
        { "word": "bitter", "translation": "苦的，痛苦的" },
        { "word": "blanket", "translation": "毯子，覆盖" },
        { "word": "candidate", "translation": "候选人，申请者" },
        { "word": "collapse", "translation": "倒塌，崩溃" },
        { "word": "cosy", "translation": "舒适的，温馨的" },
        { "word": "crew", "translation": "全体船员，机组人员" },
        { "word": "cruel", "translation": "残忍的，残酷的" },
        { "word": "crush", "translation": "压碎，粉碎" },
        { "word": "cupboard", "translation": "橱柜，碗柜" },
        { "word": "damp", "translation": "潮湿的" },
        { "word": "decent", "translation": "体面的，像样的" },
        { "word": "envy", "translation": "羡慕，嫉妒" },
        { "word": "expedition", "translation": "探险，远征" },
        { "word": "furniture", "translation": "家具" },
        { "word": "genuine", "translation": "真正的，真诚的" },
        { "word": "guidance", "translation": "指导，引导" },
        { "word": "loyal", "translation": "忠诚的，忠实的" },
        { "word": "miserable", "translation": "悲惨的，痛苦的" },
        { "word": "motive", "translation": "动机，目的" },
        { "word": "navy", "translation": "海军" },
        { "word": "nephew", "translation": "侄子，外甥" },
        { "word": "perseverance", "translation": "坚持不懈" },
        { "word": "qualified", "translation": "合格的，有资格的" },
        { "word": "recreation", "translation": "娱乐，消遣" },
        { "word": "resolve", "translation": "决心，解决" },
        { "word": "rough", "translation": "粗糙的，艰难的" },
        { "word": "selfish", "translation": "自私的" },
        { "word": "sink", "translation": "下沉，水槽" },
        { "word": "stove", "translation": "炉子，火炉" },
        { "word": "thorough", "translation": "彻底的，详尽的" },
        { "word": "torpedo", "translation": "鱼雷" },
        { "word": "unfortunate", "translation": "不幸的，倒霉的" },
        { "word": "vigour", "translation": "活力，精力" },
        { "word": "voyage", "translation": "航行，航海" },
        { "word": "wage", "translation": "工资，进行" }
      ],
      "词组": [
        { "phrase": "give off", "translation": "发出，放出" },
        { "phrase": "hold on", "translation": "坚持，等一下" },
        { "phrase": "make fire", "translation": "生火" },
        { "phrase": "turn down", "translation": "拒绝，调低" },
        { "phrase": "under one's guidance", "translation": "在某人的指导下" }
      ]
    },
    "Unit 5 Poems": {
      "词汇": [
        { "word": "amateur", "translation": "业余的，业余爱好者" },
        { "word": "await", "translation": "等待，期待" },
        { "word": "blank", "translation": "空白的，茫然的" },
        { "word": "civilian", "translation": "平民，民用的" },
        { "word": "comprehension", "translation": "理解，领悟" },
        { "word": "contest", "translation": "竞赛，比赛" },
        { "word": "correspondence", "translation": "通信，一致" },
        { "word": "dawn", "translation": "黎明，开端" },
        { "word": "deadline", "translation": "截止日期" },
        { "word": "delicate", "translation": "精致的，脆弱的" },
        { "word": "diamond", "translation": "钻石，菱形" },
        { "word": "dominance", "translation": "支配，优势" },
        { "word": "era", "translation": "时代，纪元" },
        { "word": "folk", "translation": "民间的，人们" },
        { "word": "format", "translation": "格式，版式" },
        { "word": "grief", "translation": "悲伤，悲痛" },
        { "word": "imagery", "translation": "意象，比喻" },
        { "word": "literary", "translation": "文学的，文艺的" },
        { "word": "mood", "translation": "心情，语气" },
        { "word": "nursery", "translation": "托儿所，苗圃" },
        { "word": "polish", "translation": "擦亮，润色" },
        { "word": "prejudice", "translation": "偏见，损害" },
        { "word": "prose", "translation": "散文" },
        { "word": "racial", "translation": "种族的" },
        { "word": "recite", "translation": "背诵，朗诵" },
        { "word": "respectively", "translation": "分别地，各自地" },
        { "word": "rhythm", "translation": "节奏，韵律" },
        { "word": "seed", "translation": "种子，播种" },
        { "word": "sorrow", "translation": "悲伤，悲痛" },
        { "word": "string", "translation": "弦，一串" },
        { "word": "syllable", "translation": "音节" },
        { "word": "tease", "translation": "取笑，戏弄" },
        { "word": "utter", "translation": "说出，完全的" },
        { "word": "variation", "translation": "变化，变体" },
        { "word": "verse", "translation": "诗，韵文" },
        { "word": "wherever", "translation": "无论哪里" }
      ],
      "词组": [
        { "phrase": "be made up of", "translation": "由...组成" },
        { "phrase": "in particular", "translation": "尤其，特别" },
        { "phrase": "make sense", "translation": "有意义，讲得通" },
        { "phrase": "to the point", "translation": "切题，中肯" }
      ]
    }
  }
};

if(typeof window !== "undefined" && typeof window.registerTextbookBook === "function"){
  window.registerTextbookBook("electiveBook3", electiveBook3);
}
