const electiveBook4 = {
  "选择性必修第四册": {
    "Unit 1 Science Fiction": {
      "词汇": [
        { "word": "alien", "translation": "外星人，外国的" },
        { "word": "appointment", "translation": "约会，任命" },
        { "word": "blurred", "translation": "模糊的，朦胧的" },
        { "word": "bonus", "translation": "奖金，红利" },
        { "word": "calculate", "translation": "计算，估计" },
        { "word": "chairwoman", "translation": "女主席" },
        { "word": "clerk", "translation": "职员，店员" },
        { "word": "conflict", "translation": "冲突，矛盾" },
        { "word": "dignity", "translation": "尊严，高贵" },
        { "word": "dismiss", "translation": "解雇，驳回" },
        { "word": "division", "translation": "分割，部门" },
        { "word": "fetch", "translation": "取来，拿来" },
        { "word": "fiction", "translation": "小说，虚构" },
        { "word": "flour", "translation": "面粉" },
        { "word": "guilty", "translation": "有罪的，内疚的" },
        { "word": "integrity", "translation": "正直，完整" },
        { "word": "ladder", "translation": "梯子，阶梯" },
        { "word": "leather", "translation": "皮革" },
        { "word": "nail", "translation": "钉子，指甲" },
        { "word": "pace", "translation": "步伐，速度" },
        { "word": "panel", "translation": "面板，专家组" },
        { "word": "random", "translation": "随机的，任意的" },
        { "word": "salary", "translation": "薪水，工资" },
        { "word": "science", "translation": "科学" },
        { "word": "suspend", "translation": "暂停，悬挂" },
        { "word": "whereas", "translation": "然而，鉴于" }
      ],
      "词组": [
        { "phrase": "more like", "translation": "更像是" },
        { "phrase": "on a...basis", "translation": "在...基础上" },
        { "phrase": "pros and cons", "translation": "利弊，优缺点" },
        { "phrase": "superior to", "translation": "优于，高于" },
        { "phrase": "test out", "translation": "测试，试验" },
        { "phrase": "turn out", "translation": "结果是，证明是" }
      ]
    },
    "Unit 2 Iconic Attractions": {
      "词汇": [
        { "word": "bakery", "translation": "面包店" },
        { "word": "barbecue", "translation": "烧烤" },
        { "word": "butcher", "translation": "屠夫，肉店" },
        { "word": "capacity", "translation": "容量，能力" },
        { "word": "distribution", "translation": "分配，分布" },
        { "word": "domain", "translation": "领域，域名" },
        { "word": "dynamic", "translation": "充满活力的，动态的" },
        { "word": "equator", "translation": "赤道" },
        { "word": "fence", "translation": "围栏，栅栏" },
        { "word": "frequency", "translation": "频率，频繁" },
        { "word": "golf", "translation": "高尔夫球" },
        { "word": "herb", "translation": "草药，香草" },
        { "word": "hollow", "translation": "空心的，凹陷" },
        { "word": "iconic", "translation": "标志性的，偶像的" },
        { "word": "joint", "translation": "联合的，关节" },
        { "word": "liberty", "translation": "自由，解放" },
        { "word": "license", "translation": "许可证，执照" },
        { "word": "monument", "translation": "纪念碑，遗迹" },
        { "word": "nest", "translation": "巢，窝" },
        { "word": "phase", "translation": "阶段，时期" },
        { "word": "political", "translation": "政治的" },
        { "word": "premier", "translation": "首要的，总理" },
        { "word": "prison", "translation": "监狱" },
        { "word": "sample", "translation": "样品，样本" },
        { "word": "session", "translation": "会议，学期" },
        { "word": "slogan", "translation": "标语，口号" },
        { "word": "sponsor", "translation": "赞助，赞助商" },
        { "word": "straightforward", "translation": "直接的，坦率的" },
        { "word": "temporary", "translation": "暂时的，临时的" },
        { "word": "violence", "translation": "暴力，激烈" }
      ],
      "词组": [
        { "phrase": "a flock of", "translation": "一群（鸟、羊等）" },
        { "phrase": "agree with", "translation": "同意，适合" },
        { "phrase": "do some research", "translation": "做研究" },
        { "phrase": "major in", "translation": "主修，专攻" },
        { "phrase": "peak season", "translation": "旺季，高峰期" },
        { "phrase": "pick up", "translation": "捡起，学会" }
      ]
    },
    "Unit 3 Sea Exploration": {
      "词汇": [
        { "word": "applaud", "translation": "鼓掌，赞赏" },
        { "word": "arrest", "translation": "逮捕，阻止" },
        { "word": "bond", "translation": "纽带，债券" },
        { "word": "channel", "translation": "海峡，频道" },
        { "word": "coral", "translation": "珊瑚" },
        { "word": "coverage", "translation": "覆盖，新闻报道" },
        { "word": "directory", "translation": "目录，名录" },
        { "word": "exploit", "translation": "开发，剥削" },
        { "word": "extend", "translation": "延伸，扩展" },
        { "word": "gallon", "translation": "加仑" },
        { "word": "league", "translation": "联盟，等级" },
        { "word": "log", "translation": "日志，原木" },
        { "word": "marine", "translation": "海洋的，海军的" },
        { "word": "merchant", "translation": "商人，商业的" },
        { "word": "migrate", "translation": "迁移，移居" },
        { "word": "murder", "translation": "谋杀，凶杀" },
        { "word": "negotiate", "translation": "谈判，协商" },
        { "word": "opponent", "translation": "对手，反对者" },
        { "word": "parliament", "translation": "议会，国会" },
        { "word": "royal", "translation": "皇家的，王室的" },
        { "word": "tax", "translation": "税，征税" },
        { "word": "tournament", "translation": "锦标赛，比赛" },
        { "word": "withdraw", "translation": "撤回，提取" }
      ],
      "词组": [
        { "phrase": "in a league of one's own", "translation": "独一无二，超群" },
        { "phrase": "in hand", "translation": "在掌握中，进行中" },
        { "phrase": "press conference", "translation": "新闻发布会" },
        { "phrase": "set sail", "translation": "起航，开船" },
        { "phrase": "take action", "translation": "采取行动" },
        { "phrase": "withdraw from", "translation": "从...撤出，退出" }
      ]
    },
    "Unit 4 Sharing": {
      "词汇": [
        { "word": "bubble", "translation": "泡泡，冒泡" },
        { "word": "chorus", "translation": "合唱，齐声" },
        { "word": "circuit", "translation": "电路，环形" },
        { "word": "clay", "translation": "黏土，泥土" },
        { "word": "contract", "translation": "合同，收缩" },
        { "word": "criterion", "translation": "标准，准则" },
        { "word": "deserve", "translation": "值得，应得" },
        { "word": "disability", "translation": "残疾，缺陷" },
        { "word": "drag", "translation": "拖，拽" },
        { "word": "drill", "translation": "钻孔，训练" },
        { "word": "dust", "translation": "灰尘，尘土" },
        { "word": "fireplace", "translation": "壁炉" },
        { "word": "forehead", "translation": "前额，额头" },
        { "word": "friction", "translation": "摩擦，分歧" },
        { "word": "grill", "translation": "烤架，烧烤" },
        { "word": "housing", "translation": "住房，外壳" },
        { "word": "input", "translation": "输入，投入" },
        { "word": "jam", "translation": "果酱，堵塞" },
        { "word": "kettle", "translation": "水壶" },
        { "word": "lately", "translation": "最近，近来" },
        { "word": "mail", "translation": "邮件，邮寄" },
        { "word": "mature", "translation": "成熟的" },
        { "word": "parcel", "translation": "包裹，小包" },
        { "word": "platform", "translation": "平台，站台" },
        { "word": "plug", "translation": "插头，堵塞" },
        { "word": "pray", "translation": "祈祷，恳求" },
        { "word": "privilege", "translation": "特权，荣幸" },
        { "word": "resign", "translation": "辞职，放弃" },
        { "word": "rigid", "translation": "严格的，僵硬的" },
        { "word": "ripe", "translation": "成熟的，时机成熟的" },
        { "word": "saucer", "translation": "茶碟，碟子" },
        { "word": "secondary", "translation": "次要的，中等的" },
        { "word": "shade", "translation": "阴影，遮蔽" },
        { "word": "stability", "translation": "稳定，稳定性" },
        { "word": "tablet", "translation": "药片，平板电脑" },
        { "word": "tune", "translation": "曲调，调整" },
        { "word": "uniform", "translation": "制服，统一的" },
        { "word": "vase", "translation": "花瓶" },
        { "word": "washroom", "translation": "洗手间，盥洗室" }
      ],
      "词组": [
        { "phrase": "a chorus of", "translation": "异口同声，一片" },
        { "phrase": "adapt to", "translation": "适应" },
        { "phrase": "be dying to", "translation": "渴望，极想" },
        { "phrase": "come across", "translation": "偶遇，发现" },
        { "phrase": "make a difference", "translation": "有影响，起作用" },
        { "phrase": "not to mention", "translation": "更不用说" },
        { "phrase": "relay to", "translation": "转达，传递" },
        { "phrase": "take for granted", "translation": "认为理所当然" },
        { "phrase": "to be honest", "translation": "说实话" }
      ]
    },
    "Unit 5 Launching Your Career": {
      "词汇": [
        { "word": "accountant", "translation": "会计师" },
        { "word": "accuse", "translation": "指控，谴责" },
        { "word": "acquire", "translation": "获得，学到" },
        { "word": "artificial", "translation": "人工的，人造的" },
        { "word": "assemble", "translation": "集合，装配" },
        { "word": "bounce", "translation": "弹跳，反弹" },
        { "word": "cage", "translation": "笼子，牢笼" },
        { "word": "canal", "translation": "运河，水道" },
        { "word": "categorise", "translation": "分类，归类" },
        { "word": "certificate", "translation": "证书，证明" },
        { "word": "code", "translation": "代码，密码" },
        { "word": "collar", "translation": "衣领，项圈" },
        { "word": "comfort", "translation": "舒适，安慰" },
        { "word": "debt", "translation": "债务，欠款" },
        { "word": "dedicate", "translation": "奉献，专注" },
        { "word": "desert", "translation": "沙漠，遗弃" },
        { "word": "detective", "translation": "侦探" },
        { "word": "disk", "translation": "磁盘，圆盘" },
        { "word": "estate", "translation": "房地产，财产" },
        { "word": "fry", "translation": "油炸，煎" },
        { "word": "handwriting", "translation": "笔迹，书法" },
        { "word": "intermediate", "translation": "中级的，中间的" },
        { "word": "justice", "translation": "正义，司法" },
        { "word": "knit", "translation": "编织，紧密结合" },
        { "word": "lawyer", "translation": "律师" },
        { "word": "mechanic", "translation": "机械师，技工" },
        { "word": "orient", "translation": "东方，定向" },
        { "word": "parking", "translation": "停车，停车场" },
        { "word": "participant", "translation": "参与者" },
        { "word": "profile", "translation": "侧面，简介" },
        { "word": "programming", "translation": "编程，程序设计" },
        { "word": "purse", "translation": "钱包，手提包" },
        { "word": "receipt", "translation": "收据，收条" },
        { "word": "receptionist", "translation": "接待员" },
        { "word": "sew", "translation": "缝纫，缝合" },
        { "word": "socialist", "translation": "社会主义者" },
        { "word": "spy", "translation": "间谍，侦察" },
        { "word": "supervise", "translation": "监督，管理" },
        { "word": "wrist", "translation": "手腕" }
      ],
      "词组": [
        { "phrase": "attend to", "translation": "照料，处理" },
        { "phrase": "be accused of", "translation": "被指控" },
        { "phrase": "be passionate about", "translation": "对...充满热情" },
        { "phrase": "head start", "translation": "领先优势" }
      ]
    }
  }
};

if(typeof window !== "undefined" && typeof window.registerTextbookBook === "function"){
  window.registerTextbookBook("electiveBook4", electiveBook4);
}
